### ISSUE TITLE
Unify properties into a LoggerContext-scoped properties system

### ISSUE THREAD

**Issue by jvz** [apache/logging-log4j2#1201]
https://cwiki.apache.org/confluence/display/LOGGING/Properties+Enhancement

Also, first!

**Comment by ppkarwasz** [comment]
@jvz, didn't we complete this one?

**Comment by jvz** [comment]
Generally speaking, yes, though I was still going to investigate some straggler properties that don't actually support per-context properties but should.

**Comment by jvz** [comment]
Actually, this was completed in https://issues.apache.org/jira/browse/LOG4J2-3299 and in #1473.
