### ISSUE TITLE
Enforce signed commits

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#1207]
As [discussed in the mailing list](https://lists.apache.org/thread/9d53znkksfkw0rkmgb4pk1ws95m4y3nb), we better enforce signed commits in the repository. This better be reflected in [a GitHub Pull Request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) along with some other checks:

- Changelog entry
- Signed commits
- Tests
- etc.

**Comment by ppkarwasz** [comment]
- running `spotless:apply`

**Comment by vy** [comment]
> * running `spotless:apply`

Is this really necessary given it is part of the build? It sounds like _"building the sources"_ or am I exaggerating?

**Comment by ppkarwasz** [comment]
@vy,

`spotless:check` is part of the build. We should document `spotless:apply` there so that contributors don't have to wonder why the build failed.

**Comment by vy** [comment]
Fixed in c6019c979ac07c1e664d066d01302561b47d2c72 and b61fd7b7fb5e9036b915992d5fa5522e72e424ae.
