### ISSUE TITLE
Hybrid example uses wrong class

### ISSUE THREAD

**Issue by Deceptio** [apache/logging-log4j2#1211]
It seems that this example is not quite correct on line 28? 
[Hybrid Example](https://logging.apache.org/log4j/2.x/manual/customconfig.html#Hybrid)

There is no XMLConfiguration class but only an XmlConfiguration class. 
Additionally the method createLogger is deprecated. 
And the variable "refs" is also not defined anywhere

Maybe you should write a new example for the hybrid application.

But maybe I understand the API wrong.

**Comment by aawad6** [comment]
Fixed in https://github.com/apache/logging-log4j2/commit/0269ce259b6875c6082207970e81b14d56cb4444.

**Comment by vy** [comment]
Fixed in #1478.
