### ISSUE TITLE
FormattedMessage doesn't need to use regular expressions

### ISSUE THREAD

**Issue by jvz** [apache/logging-log4j2#1223]
In order to determine which message format syntax to use in `FormattedMessage`, this uses a regular expression. This can be simplified by flipping the ordering to check for a parametrized message first before assuming it's a printf-style message.

**Comment by adwsingh** [comment]
@jvz I was looking into this. How do you suggest we check for a parametrized message, by doing `countArgumentPlaceholders(msg) > 0` ?

**Comment by ppkarwasz** [comment]
@adwsingh, that sounds about right.

I marked you as "assignee" to prevent other contributors to work on it. It's not an obligation.

**Comment by ppkarwasz** [comment]
@adwsingh,

Yes, it is a breaking change to silence [Code scanning alert #51](https://github.com/apache/logging-log4j2/security/code-scanning/51): checking for an unescaped `{}` is much faster than checking for a `java.util.Formatter` format specifier.

I believe we can change the documentation to state:

> The message factory supports the following format specifiers:
> * those specified by `java.text.MessageFormat`,
> * those specified by `java.util.Formatter`,
> * `{}` placeholders (cf. `ParameterizedMessage`).
> Mixing specifier from these 3 categories is not supported.

BTW: The regex we use currently is identical to `java.util.Formatter.formatSpecifier` used by the JRE, so this does not change anything security-wise.
