### ISSUE TITLE
Log4jLoggingNode jar is not available in version 2.x

### ISSUE THREAD

**Issue by nagkalgur** [apache/logging-log4j2#1228]
## Description
currently our logging framework is implemented with 1.2.17 log4j jar. we have got vulnerability from security team to use latest version 2.x of Log4j but current version doesn't have Log4jLoggingNode jar.
[A clear and concise description of what the bug is.]

## Configuration

**Version:** [Log4j version]
1.2.17
**Operating system:** [OS and version]
Redhat Linux
**JDK:** [JDK distribution and version]

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
```

## Reproduction

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by nagkalgur** [comment]
HI,
is there any workaround for this. how can we log4jLogging node jar in latest Log4j version 2.x

**Comment by ppkarwasz** [comment]
@nagkalgur,

`Log4jLoggingNode.jar` seems to be a private library at your company. Can you explain what it does? Maybe it is possible to replace it with standard components.

**Comment by nagkalgur** [comment]
this github location has the details log4jLogging node

https://github.com/ot4i/node-for-log4j

**Comment by rgoers** [comment]
Well, that repo is NOT part of Log4j and never has been. I have no idea what it does but if it is missing something I suggest you ask the maintainers of that project.
