### ISSUE TITLE
(doc) Missing taglib documentation

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1230]
The "Tag library reference" disappeared after version 2.17.1, while the "TLDDoc documentation" disappeared after version 2.17.2:

https://logging.apache.org/log4j/2.x/log4j-taglib/index.html

**Comment by vy** [comment]
The page is available under [https://logging.apache.org/log4j/2.x/log4j-taglib.html], which is linked from the menu. That should be good enough for this hardly ever used component, right?

**Comment by ppkarwasz** [comment]
@vy,

The `taglib-maven-plugin` has been relaunched: https://github.com/weblegacy/taglib-maven-plugin
Maybe we could generate that part of the documentation again?

**Comment by vy** [comment]
@ppkarwasz, mind elaborating on your proposal a bit, please? What exactly do you want to replace in the current setup with `taglib-maven-plugin`s which functionality?

**Comment by ppkarwasz** [comment]
@vy,

Before version 2.17.2 the Log4j Taglib module had a:

- [Tagreference documentation](https://logging.apache.org/log4j/log4j-2.15.0/log4j-taglib/tagreference),
- [TLDoc documentation](https://logging.apache.org/log4j/log4j-2.15.0/log4j-taglib/tlddoc/).

We should be able to restore this documentation using the plugin from the `weblegacy` project.

**Comment by vy** [comment]
The way I see this proposal is as follows:

We will add a Maven plugin configuration and probably HTML redirects (involving `.htaccess` edits and such) for a module that
1. after a long period of user feedback, is announced to be removed
2. nobody complained about its missing docs
3. Nexus stats indicate no usage

Hence, I give -1 for chasing this further. I would rather have a `pom.xml` that is clean from one more relic.
