### ISSUE TITLE
log4j-to-slf4j not working with slf4j v2

### ISSUE THREAD

**Issue by Hakky54** [apache/logging-log4j2#1232]
## Description
I am using log4j-to-slf4j to forward all log4j calls to slf4j for my library [LogCaptor](https://github.com/Hakky54/log-captor). At August 2022 slf4j maintainers released version 2 which does not work anymore with `log4j-to-slf4j`. Would it be possible to make it compatible again?

A workaround for me would be forwarding log4j calls to jul and use that, but that I would not be able to use MDC for example and that is the reason why I am hoping that log4j-to-slf4j could be compatible with the latest slf4j release.

[A clear and concise description of what the bug is.]
Non log calls are being sent to slf4j (tested with v2.0.6) from log4j (tested with v2.19.0)

## Configuration

**Version:** 2.19.0

**Operating system:** any

**JDK:** oracle jdk 1.8

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
```

## Reproduction
Git fork and clone: https://github.com/Hakky54/log-captor
Adjust the slf4j version to 2.0.6 and run the test with `mvn verify`

**Comment by Hakky54** [comment]
Nevermind, I had a dependency management issue with dependencies having different versions. There is no issue, so I am closing it.

**Comment by HannesWell** [comment]
In the OSGi world it is currently indeed impossible to use log4j-to-slf4j in conjunction with slf4j-2 because the Manifest only imports the slf4j packages only up until, but excluding 2:
```
Import-Package:
 [...]
 org.slf4j;version="[1.7,2)",
 org.slf4j.spi;version="[1.7,2)"
```
If log4j-to-slf4j works well with slf4j 1 and 2 I suggest to widen the package import range to "[1.7,3)".
If the log4j maintainers are interested I can provide a corresponding PR.

**Comment by ppkarwasz** [comment]
@HannesWell,

Sure, PRs are welcome. We use `maven-bundle-plugin` to generate the OSGI manifest.

**Comment by Hakky54** [comment]
By the way guys, just out of curiosity, how come this situation works for my library with logcaptor using slf4j v2 and latest version of log4j-to-slf4j, but not working for the OSGi world?

**Comment by HannesWell** [comment]
> By the way guys, just out of curiosity, how come this situation works for my library with logcaptor using slf4j v2 and latest version of log4j-to-slf4j, but not working for the OSGi world?

Because non OSGi applications usually don't care about the OSGi metadata. But the OSGi metadata said that log4j-to-slf4j required slf4j in version `[1.7,2)`. Therefore an OSGi runtime refused to resolve the `log4j.to-slf4j` if only slf4j1.7.x is available.
