### ISSUE TITLE
API tests failing on running  ./mvnw verify

### ISSUE THREAD

**Issue by muskaan2199** [apache/logging-log4j2#1260]
I am trying to build and test on ppc64le(ubi). However the API tests fail on running the `./mvnw` verify command. I've installed jdk 8, 9 and 11 and added it to toolchains.cml file.

>[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ServiceLoaderUtilTest.testBrokenServiceFile:88 expected: <2> but was: <1>
[INFO]
[ERROR] Tests run: 681, Failures: 1, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Log4j 2 2.19.1-SNAPSHOT:
[INFO]
[INFO] Apache Log4j 2 ..................................... SUCCESS [  2.476 s]
[INFO] Apache Log4j API Java 9 support .................... SUCCESS [  3.274 s]
[INFO] Apache Log4j API ................................... SUCCESS [  1.749 s]
[INFO] Apache Log4j Implementation Java 9 support ......... SUCCESS [  0.446 s]
[INFO] Apache Log4j Core .................................. SUCCESS [  1.799 s]
[INFO] Apache Log4j API Tests ............................. FAILURE [ 16.645 s]
[INFO] Apache Log4j Core Tests ............................ SKIPPED
[INFO] Apache Log4j 1.x Compatibility API ................. SKIPPED
[INFO] Apache Log4j App Server Support .................... SKIPPED
[INFO] Apache Log4j BOM ................................... SKIPPED
[INFO] Apache Log4j to SLF4J Adapter ...................... SKIPPED
[INFO] Apache Log4j SLF4J Binding ......................... SKIPPED
[INFO] Apache Log4j Cassandra ............................. SKIPPED
[INFO] Apache Log4j Core Integration Tests ................ SKIPPED
[INFO] Apache Log4j CouchDB ............................... SKIPPED
[INFO] Apache Log4j Docker Library ........................ SKIPPED
[INFO] Apache Log4j Commons Logging Bridge ................ SKIPPED
[INFO] Apache Log4j Flume Bridge .......................... SKIPPED
[INFO] Apache Log4j Streaming Interface ................... SKIPPED
[INFO] Apache Log4j Jakarta SMTP .......................... SKIPPED
[INFO] Apache Log4j Jakarta Web ........................... SKIPPED
[INFO] Apache Log4j JPA ................................... SKIPPED
[INFO] Apache Log4j JDK Platform Logging Adapter .......... SKIPPED
[INFO] Apache Log4j JDBC DBCP 2 ........................... SKIPPED
[INFO] Apache Log4j JMX GUI ............................... SKIPPED
[INFO] Apache Log4j JUL Adapter ........................... SKIPPED
[INFO] Apache Log4j Kubernetes Library .................... SKIPPED
[INFO] Apache Log4j Layout for JSON template .............. SKIPPED
[INFO] Apache Log4j Layout for JSON template Tests ........ SKIPPED
[INFO] Apache Log4j Liquibase Binding ..................... SKIPPED
[INFO] Apache Log4j MongoDB 3 ............................. SKIPPED
[INFO] Apache Log4j MongoDB 4 ............................. SKIPPED
[INFO] Apache Log4j to JUL Bridge ......................... SKIPPED
[INFO] Apache Log4j OSGi .................................. SKIPPED
[INFO] Apache Log4J Performance Tests ..................... SKIPPED
[INFO] Apache Log4j Samples ............................... SKIPPED
[INFO] Apache Log4j Samples: Flume - Common ............... SKIPPED
[INFO] Apache Log4j Samples: Flume - Remote ............... SKIPPED
[INFO] Apache Log4j Samples: Flume - Embedded ............. SKIPPED
[INFO] Apache Log4j Samples: Configuration ................ SKIPPED
[INFO] Apache Log4j Samples: LoggerProperties ............. SKIPPED
[INFO] Apache Log4j SLF4J 2.0 Binding ..................... SKIPPED
[INFO] Apache Log4j Spring Boot Support ................... SKIPPED
[INFO] Apache Log4j Spring Cloud Config Support ........... SKIPPED
[INFO] Apache Log4j Spring Cloud Config Client Support .... SKIPPED
[INFO] Apache Log4j Spring Cloud Config Samples ........... SKIPPED
[INFO] Apache Log4j Sample Configuration Service .......... SKIPPED
[INFO] Apache Log4j Spring Cloud Config Sample Application  SKIPPED
[INFO] Apache Log4j Web ................................... SKIPPED
[INFO] Apache Log4j Tag Library ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.831 s
[INFO] Finished at: 2023-01-31T05:06:57Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project log4j-api-test: There are test failures.
[ERROR]
[ERROR] Please refer to /logging-log4j2/log4j-api-test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :log4j-api-test`

**Comment by ppkarwasz** [comment]
@muskaan2199,

Is this reproducible? Which JRE is running the tests?

**Comment by muskaan2199** [comment]
> @muskaan2199,
> 
> Is this reproducible? Which JRE is running the tests?

The output of `java -version`
>openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

**Comment by ppkarwasz** [comment]
@muskaan2199,

Our `release-2.x` build is meant to be run using JDK 8 (we should add an enforcer rule for that). Set `JAVA_HOME` to the path of your JDK 8 installation.

On Java 9 the `ServiceLoaderUtilTest` fails in a non-essential way (one of the "broken" service entries is ignored by JDK 9, while we expect to ignore them ourselves; the result is the same). You can try #1263 for an improved version of the test, that should also work on JDK 9+.
