### ISSUE TITLE
Detect suppliers passed as `Object` parameters

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1262]
## Description

While logger methods with `Supplier<?>` in the signature are the easiest way to log lazily, we should also detect when users pass suppliers as `Object` parameters. It would be nice if:

```lang-java
log.info("The {} {} {} jumps over the {}.", brown, quick, fox, (Supplier<?>) () -> "lazy dog");
```

gave the same result as:

```lang-java
log.info("The {} {} {} jumps over the {}.", () -> brown, () -> quick, () ->fox, () -> "lazy dog");
```

## References

This proble appears in a [StackOverflow question](https://stackoverflow.com/q/75326876/11748454), but probably in many more.

**Comment by rgoers** [comment]
I do not believe this is practically solvable using the standard API. However, I propose we enhance the LogBuilder to support this so you would code:
```
log.atInfo().withArg(() -> quick).withArg(() -> brown).withArg("fox").withArg(() -> "lazy dog").log("The {} {} {} jumps over the {}.");
```
We could also do 
```
log.atInfo().withMsg("The {} {} {} jumps over the {}.").withArg(() -> quick).withArg(() -> brown).withArg("fox").withArg(() -> "lazy dog").log();
```

**Comment by ppkarwasz** [comment]
I have to agree, I initially thought that we can call `Supplier#get()` on each parameter that implements `Supplier`. However in doing so we prevent users from logging objects that accidentally also implement `Supplier`, e.g. a factory might implement `Supplier`, but the user might want to log the factory's name instead.
