### ISSUE TITLE
RewriteAppender ignores the location requirement of its appenders

### ISSUE THREAD

**Issue by amirhadadi** [apache/logging-log4j2#1274]
Currently `RewriteAppender` does not override `requiresLocation` from `AbstractAppender` making `RewriteAppender::requiresLocation` always return `false`. This results in the location not being passed to its underlying appenders when needed.
Instead, `RewriteAppender::requiresLocation` should return true when any of its appenders requires a location.

**Comment by ppkarwasz** [comment]
@amirhadadi,

Thank you for noticing, it will be fixed in the next release. Can you check if the latest `2.19.1-SNAPSHOT` available on https://repository.apache.org/snapshots fixes your problem?

**Comment by amirhadadi** [comment]
@ppkarwasz that version fixes the issue. Thanks for the quick fix!
