### ISSUE TITLE
Fix locale-dependent `toLowerCase()/toUpperCase()` calls

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1281]
Log4j2 has a couple of remaining call sites of `String#toLowerCase` and `String#toUpperCase`, which are locale-dependent. These calls should be replaced with `Strings#toRootLowerCase` and `Strings#toRootUpperCase`.

Such a call is present for example in `PluginManager`, which causes `IfLastModified` to be transformed to `ıflastmodified` (with a dotless i), if the locale is Turkish (cf. [this SO question](https://stackoverflow.com/q/51538312/11748454)).

**Comment by ppkarwasz** [comment]
I think this can be a good first issue: there are already helper methods [`Strings#toRootLowerCase`](https://logging.apache.org/log4j/2.x/javadoc/log4j-api/org/apache/logging/log4j/util/Strings.html#toRootLowerCase-java.lang.String-) and [`Strings#toRootUpperCase`](https://logging.apache.org/log4j/2.x/javadoc/log4j-api/org/apache/logging/log4j/util/Strings.html#toRootUpperCase-java.lang.String-).

**Comment by akashshirale14** [comment]
Can you assign this issue to me?

**Comment by ppkarwasz** [comment]
@akashshirale14,

Done. I also updated the issue description: we already have methods `Strings#toRootLowerCase/toRootUpperCase` that sound less English-centric and do the same thing.

**Comment by AmmarYasser97** [comment]
Hello, @akashshirale14 
Are you still working on this issue?, I'm interested to work on it.

**Comment by akashshirale14** [comment]
Hi Ammar,
                 Yes, you can take it.

Regards,
Akash Shirale
