### ISSUE TITLE
Hide PosixViewAttribute related error info in Windows

### ISSUE THREAD

**Issue by smalljunHw** [apache/logging-log4j2#1283]
I use PosixViewAttribute to set file permission
```xml
            <DefaultRolloverStrategy max="4">
                <PosixViewAttribute basePath="${LOG_HOME}" filePermissions="r--------">
                    <IfFileName glob="*.gz" />
                </PosixViewAttribute>
            </DefaultRolloverStrategy>
```
When I start my project in Windows (like in Intellij IDEA), I got the following error info.
```bash
main ERROR Null object returned for PosixViewAttribute in DefaultRolloverStrategy
```
Though it seems that log still functions properly, how can I make the error info disappear?
BTW:  I do know taht PosixViewAttribute  should only work on Linux, but I want to keep the configuartion to be same in both the Windows and Linux.

**Comment by ppkarwasz** [comment]
@smalljunHw,

Should we replace the `ERROR` message with a more appropriate `WARN` message?
