### ISSUE TITLE
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by nameisjayant** [apache/logging-log4j2#1288]
Hello basically i am using log4j library and this support minSdk 26 and currently i am using minSdk 21 but the problem is i cannot upgrade minSdk version to 26 .

So is there any way to compatible midSdk 21 to 26 .. Any help would be appreciated

**Comment by ppkarwasz** [comment]
@nameisjayant,

Although version 2.x has a baseline of Java 8, most of our users nowadays runs Java 11 or Java 17. That is why we must (at least partially) support JPMS.

We introduced the `MethodHandle#invokeExact` call in [`ServiceLoaderUtil`](https://github.com/apache/logging-log4j2/blob/rel/2.18.0/log4j-api/src/main/java/org/apache/logging/log4j/util/ServiceLoaderUtil.java) for this exact reason, starting from version 2.18.0. I don't see a way to remove it.

As a workaround, you can use version 2.17.2.
