### ISSUE TITLE
log4j-core test-jar not published to Maven Central for 2.20.0 release

### ISSUE THREAD

**Issue by norrisjeremy** [apache/logging-log4j2#1291]
## Description

The log4j-core test-jar  for 2.20.0 does not appear to be published to Maven Central.

## Configuration

**Version:** 2.20.0

**Operating system:** n/a

**JDK:** n/a

## Logs

```
Could not find artifact org.apache.logging.log4j:log4j-core:jar:tests:2.20.0 in central (https://repo.maven.apache.org/maven2), try downloading from https://logging.apache.org/log4j/2.x/download.html -> [Help 1]
```

## Reproduction

Add the following dependency into pom.xml and see it fail to download:
```
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-core</artifactId>
  <version>2.20.0</version>
  <type>test-jar</type>
</dependency>
```

**Comment by norrisjeremy** [comment]
Has the name of this artifact changed?
I now see this artifact on Maven Central:
```
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-core-test</artifactId>
  <version>2.20.0</version>
</dependency>
```

If so, it would be nice if that this change was denoted in the release notes at https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html.

**Comment by ppkarwasz** [comment]
@norrisjeremy,

Yes, the tests have been refactored, cf. [LOG4J2-3650](https://issues.apache.org/jira/browse/LOG4J2-3650).

We'll regenerate the release notes soon.

**Comment by norrisjeremy** [comment]
Hi @ppkarwasz,

Ok, thanks.
FYI, the package names appear to be different in this new artifact, so that should probably be denoted (easy enough to fix though).

However, this new artifact also seems to drag in a bunch of dependencies: was that intended?

We're going to end up adding this to avoid dragging in all this extraneous stuff:
```
<exclusions>
  <exclusion>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api-test</artifactId>
  </exclusion>
  <exclusion>
    <groupId>org.assertj</groupId>
    <artifactId>assertj-core</artifactId>
  </exclusion>
  <exclusion>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
  </exclusion>
  <exclusion>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
  </exclusion>
  <exclusion>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest</artifactId>
  </exclusion>
  <exclusion>
    <groupId>com.google.code.java-allocation-instrumenter</groupId>
    <artifactId>java-allocation-instrumenter</artifactId>
  </exclusion>
  <exclusion>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
  </exclusion>
  <exclusion>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-commons</artifactId>
  </exclusion>
  <exclusion>
    <groupId>org.springframework</groupId>
    <artifactId>spring-test</artifactId>
  </exclusion>
</exclusions>
```

Thanks,
Jeremy

**Comment by ppkarwasz** [comment]
@norrisjeremy,

I took care of the [release notes](https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html).

The difference in dependencies is caused by Maven:

* for the `log4j-core` artifact with `tests` classifier Maven pulled the wrong dependencies (`compile` scope instead of `test` scope),
* for the `log4j-core-test` artifact the real dependencies are no longer hidden: the artifact mostly contains JUnit 4 and JUnit 5 extensions, so it depends on all those libraries.
