### ISSUE TITLE
Can I read the log4j.xml without loading it with the API.

### ISSUE THREAD

**Issue by KTonev** [apache/logging-log4j2#1361]
Hello, so I want to get the value of fileName as a String from an appender. But when I use the Log4j 2 API, it loads the log4j.xml and creates files with the value inside of "fileName". I understand why it works that way but I want to ask if there is a way to read the log4j.xml, get the value of "fileName" as a String from the appender without loading it and creating files, that done with Log4j2 API. Because I have running server at the same time using that log4j.xml and I don't want the API loading it at the same time. So I am interested in that if the API can just read the xml file something like parser.
Thank you for your answer in advance!!!

**Comment by vy** [comment]
As [our support](https://logging.apache.org/log4j/2.x/support.html) and [the GitHub Issue template you used to write this ticket](/apache/logging-log4j2/blob/2.x/.github/ISSUE_TEMPLATE/question.md) states, please use mailing lists for questions.

**Comment by KTonev** [comment]
https://lists.apache.org/list.html?log4j-user@logging.apache.org 
Is this an appropriate list?

**Comment by vy** [comment]
@KTonev, yes.
