### ISSUE TITLE
Request to expose certain protected APIs as public

### ISSUE THREAD

**Issue by Karthi1711** [apache/logging-log4j2#1365]
Hello,

I would like to request that certain APIs which are currently protected be exposed as public for broader access. Specifically, I am interested in accessing `createCompressAction()`, `getExtension()`, `length()` in `FileExtension` enum for customized rollover strategy which we have written at our end. 

Could you please consider this request and let me know if it is possible to make these APIs public? I would be happy to provide more information or answer any questions you may have.

Thank you for your time and consideration.

Best regards,
Karthi

**Comment by ppkarwasz** [comment]
Hello @Karthi1711,

Can You submit a PR with the changes?

**Comment by garydgregory** [comment]
I think we want to be careful here @ppkarwasz: Do we really want to lock down an API as public for such low level classes and be bound to binary compatibility? Or are we going to say this class is not part of BC?

**Comment by ppkarwasz** [comment]
@garydgregory,

I would just prefer to see this request in the form of a PR, that we can discuss on the code.

**Comment by Karthi1711** [comment]
PR created: https://github.com/apache/logging-log4j2/pull/1683.
