### ISSUE TITLE
Link on page is dead

### ISSUE THREAD

**Issue by Betalord** [apache/logging-log4j2#1376]
Not sure where to report this, so I'm reporting it here.
The link at this page is dead:
https://logging.apache.org/log4j/2.x/log4j-iostreams.html
In this sentence: "`For more information, see [Runtime Dependencies](https://logging.apache.org/log4j/runtime-dependencies.html).`"
The link provided leads to a 404 page.

**Comment by vy** [comment]
Thanks so much for the report @Betalord! :pray:
I have fixed that one and dozens of others in the component pages.
