### ISSUE TITLE
Initializing Log4j1 bridge with properties object blocks Log4j2 logging since 2.17.2

### ISSUE THREAD

**Issue by mbain-cincom** [apache/logging-log4j2#1382]
## Description
We have a legacy class that loads Log4J using PropertyConfigurator.configure(Properties) via the bridge libraries.  Since 2.17.2, once this line is hit our Log4j2 statements will stop logging.  I have been able to replicate through 2.20.  Changing between 2.17.1 and 2.17.2 in the attached Maven project will replicate the before and after scenarios.

## Configuration

**Version:** 2.17.2

**Operating system:** Windows Server 2012

**JDK:** 1.8 - 11

## Reproduction
Project attached
[Log4J2Issue.zip](https://github.com/apache/logging-log4j2/files/11023540/Log4J2Issue.zip)

**Comment by ppkarwasz** [comment]
`PropertyConfigurator#configure()` was a no-op before version 2.17.2 (cf. [source code](https://github.com/apache/logging-log4j2/blob/rel/2.17.1/log4j-1.2-api/src/main/java/org/apache/log4j/PropertyConfigurator.java)).

The call must provide a broken configuration (you can debug it by running `-Dlog4j2.debug=true`), hence the logs vanish.

**Comment by mbain-cincom** [comment]
@ppkarwasz 

Thank you for the reply, it filled in the piece I was missing.  It wasn't a broken configuration, rather an incorrect mindset on my part.  Previously this application was using Log4j2 and Log4j1 for independent purposes.  In 2.17.1 we were able to get the proper result based on the configure() option not doing anything and having a logger that matched in our log4j2.xml.  As soon as it was actually performing an initialization it is now overwriting our log4j2 configuration with our legacy Log4j1 configuration, and our Log4j2 usage in essence no longer has loggers to work with.  We will have to look into potential solutions either through context or creating a custom configuration factory, etc.

**Comment by ppkarwasz** [comment]
There is an open JIRA issue ([LOG4J2-3467](https://issues.apache.org/jira/browse/LOG4J2-3467)) to provide users a way to disable the improvement in `log4j-1.2-api` introduced in version 2.17.2. We should probably consider it solving it.
