### ISSUE TITLE
Log4J2 getting stuck when reconfiguring it

### ISSUE THREAD

**Issue by contivero** [apache/logging-log4j2#1399]
## Description
[I described this in SO](https://stackoverflow.com/questions/75817456/log4j2-sometimes-gets-stuck-when-reconfiguring-it) and was told to file an issue here.

After trying to reconfigure Log4J2 with [the method suggested in the docs](https://stackoverflow.com/questions/75817456/log4j2-sometimes-gets-stuck-when-reconfiguring-it), our application gets stuck. This happens only sometimes, and I've had it never happen locally, but happens with certain frequency in our production system, and another test system which is more or less a copy of the one in production (both run in a cluster, not sure if that's related or not). Usually in those cases we just kill the stuck nodes and try starting them up again.

## Configuration

**Version:** Log4j2 2.19.0

**Operating system:** CentOS Linux release 7.9.2009 (Core)

**JDK:** 
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

## Logs
I tried debugging one such instance, the following is a screenshot of that:

![Screenshot 2023-01-13 at 11 43 52](https://user-images.githubusercontent.com/1451663/228226940-7263a8cf-8cd5-48d3-9d2f-67dee592c983.png)

As far as I can understand, Log4J2 is in a loop waiting for some log event to finish (which pressumably would decrease the counter variable in `AwaitCompletionReliabilityStrategy.afterLogEvent()`, but this is never called, and so the counter is always 1 and the loop repeats indefinitely). When I was remote debugging this, I couldn't find any other thread in the middle of some logging call.

I also have the following threaddump that we got from another such instance in our production system:

[pwweb06_threaddump_20230312_0943.txt.zip](https://github.com/apache/logging-log4j2/files/11088908/pwweb06_threaddump_20230312_0943.txt.zip)

I also don't see anything related to a different thread logging while the main thread is stuck in `AwaitCompletionReliabilityStrategy`.

## Reproduction

I'm sorry that I don't have a small reproduction that could help you track this down, I'm still trying to find a reliable one myself, but will leave a comment if I learn anything new in the upcoming days.

**Comment by ppkarwasz** [comment]
@contivero,

Could you tell us more about your configuration? You seem to have a positive value of `counter`, but no thread is currently logging.

@carterkozak, do you see something wrong in `AwaitCompletionReliabilityStrategy`?

**Comment by contivero** [comment]
This is the configuration picked up automatically by Log4J2 on start up (if that's what you are asking):
```
<Configuration>
	<Appenders>
		<Console name="CONSOLE">
			<PatternLayout pattern="%-5p [%d{yyyy-MM-dd HH:mm:ss,SSS}] %c{1}: %m%ex%n" />
		</Console>
	</Appenders>

	<Loggers>
		<Logger name="at.workflow" level="INFO" additivity="false">
			<AppenderRef ref="CONSOLE" />
		</Logger>

		<Logger name="org.springframework" level="INFO" additivity="false">
			<AppenderRef ref="CONSOLE" />
		</Logger>

		<Root level="ERROR">
			<AppenderRef ref="CONSOLE" />
		</Root>
	</Loggers>
</Configuration>
```
I've tried reproducing it locally with jetty ran through Eclipse, but it works fine. I believe the systems that are showing the issue both run with Tomcat (which is something I'm yet to attempt). In the thread dump I posted above the only other remote mentions to anything to do with logs I found were:

1. `AsyncFileHandlerWriter-863831416`, which mentions `at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:204)`.
2. `FileHandlerLogFilesCleaner-1`

but both seem to be related to log files, and as you can see our initial config is quite barebones and only logging to the console. The one we load later has RollFileAppenders and some other stuff. I can also post that if needed, but I assume it doesn't matter since it's getting stuck while "closing" the previous configuraiton, the new one doesn't come into play yet (unless I'm mistaken).

**Comment by contivero** [comment]
When I was going through the AwaitCompletionReliabilityStrategy code it looked fine, and I'm now leaning towards thinking the issue is not a Log4J2 one. The thing is, we had a `StackOverflowError` which was being swallowed because of a library catching `Throwable`. Normally this wouldn't be noticed, or if it happened, still the server would start up and be functional. We've now fixed this, and during the last deployment to production which included this fix, no node got stuck when refreshing the Log4J2 settings. Searching around I've found that [a StackOverflowError can cause finally blocks to be skipped](https://bugs.openjdk.org/browse/JDK-8177802), which would explain the Log4J2 incorrect counter. I'll wait some more days, see if I can reproduce it next week. If not, I guess we can assume that was the cause and you can close the issue.

**Comment by contivero** [comment]
I'll close this, as we haven't had any issues since fixing the StackOverflowError which was being swallowed. Clearly when the finally block to decrease the counter tried to run it was bumping into another StackOverflowError, preventing the decrement, leaving AwaitCompletionReliabilityStrategy in an invalid state. In any case thanks! And sorry for the misplaced issue.

**Comment by ppkarwasz** [comment]
@contivero, thank you for debugging this issue.
