### ISSUE TITLE
log4j2 configuring ColumnMapping type using properties format

### ISSUE THREAD

**Issue by G0-G4** [apache/logging-log4j2#1405]
## Description

It is impossible to provide ColumnMapiing type in properties format.

For example I want to write `journal_id` in database as an integer. I can't write something like this

```
appender.message_appender.columnMappings[1].type = ColumnMapping
appender.message_appender.columnMappings[1].name = journal_id
appender.message_appender.columnMappings[1].type = java.lang.Integer # can't have two type parameters
```

## Configuration

**Version:** 2.11.0

**Operating system:** windows 10

**JDK:** OpenJDK 17.0.2

**Comment by ppkarwasz** [comment]
@G0-G4,

We'll try to fix the problem in the next release by adding an alternative name for the `type` property.

BTW: you are using a version with several security vulnerability. Upgrade to the latest one.
