### ISSUE TITLE
Date and time patterns should follow `DateTimeFormatter`

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1416]
In release 2.x date time patterns follow [`SimpleDateFormat`](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) with additional extensions provided by [`FastDateFormat`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/FastDateFormat.html) and support for the `n` specifier for nanoseconds.

The exception is JSON Template Layout, which uses the format specifiers from [`DateTimeFormatter`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html).

In release 3.x we should switch all format specifiers to those documented `DateTimeFormatter`.

The major differences are:

 * `u` means day-of-week in SDF and era in DTF,
 * SDF lacks `L` meaning month as text,
 * SDF lacks `q` and `Q` as quarter,
 * in DTF `Z`, `ZZ` and `ZZZ` all mean the same format for the time zone (e.g. `-0800`, `+0000`). In SDF (Commons Land version) `ZZ` uses the ISO 8601 format with a colon (e.g. `-08:00`, `Z`) and `ZZZ` adds a colon to the original `Z` format (e.g. `-08:00`, `+00:00`).

**Comment by vy** [comment]
Even though this will be a (slightly?) breaking change, can't we rather implement this on `2.x`? As long as we clearly indicate this in release notes, this feels legit to me. @rgoers, WDYT?

**Comment by garydgregory** [comment]
SDT -> SDF?

**Comment by ppkarwasz** [comment]
Fixed by #3150.
