### ISSUE TITLE
about use log4j2 2.2-verison write logs data to clickhouse,write data use jdbc PreparedStatement ,but execute connection.PrepareStatement,this method excute Exception! 

### ISSUE THREAD

**Issue by caiyao199289** [apache/logging-log4j2#1417]
As clearly indicated in [the Log4j support page](https://logging.apache.org/log4j/2.x/support.html#issues), **please use mailing lists for questions!**

java.sql.SQLException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath., server ClickHouseNode 

question:
 hello, can I ask you question,about use log4j2 2.2-verison write logs data to clickhouse,write data use jdbc PreparedStatement ,but execute connection.PrepareStatement,this method excute Exception!

**Comment by ppkarwasz** [comment]
@caiyao199289,

Please send your questions to the [`log4j-user@logging.apache.org`](https://logging.apache.org/log4j/2.x/support.html#discussions) mailing list (or post a question tagged `log4j2` on StackOverflow).
