### ISSUE TITLE
Stray unicode character

### ISSUE THREAD

**Issue by jwmelto** [apache/logging-log4j2#1449]
## Description

While trying to build log4j from source (provided by a third party), in some context that I could not isolate, the build fails because of a single unicode character [here](https://github.com/apache/logging-log4j2/blob/2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/appender/AsyncAppenderEventDispatcher.java#L175).

Given that there is no compelling reason for unicode in this file (at all, much less in a comment), I would suggest it be removed.

## Configuration

**Version:** [2.17.1]

**Operating system:** [RHEL 8 (ubi8)] (building in a container)

**JDK:** [OpenJDK 1.8.0_372]

## Logs
```
Building log4j_core_java 2.17.1 with ant
/usr/src/project/dependencies/log4j_core_java/2.17.1 /usr/src/project/dependencies/log4j_core_java/2.17.1 /usr/src/project
/usr/src/project/dependencies/log4j_core_java/2.17.1/src/main/java/org/apache/logging/log4j/core/appender/AsyncAppenderEventDispatcher.java:164: error: unmappable character for encoding ASCII
        // ??? ckozak)
           ^
```

## Reproduction

(I was unable to identify a sufficient minimal reproducible test; OTOH, the unicode character is self-evident)

**Comment by ppkarwasz** [comment]
@jwmelto,

Thank you for your report.

All Log4j source files and resources are encoded using UTF-8. You can find this information in the POM file:

```
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

Since you are using Ant instead of Maven, you should use equivalent settings: cf. the `encoding` parameter for the [Javac task](https://ant.apache.org/manual/Tasks/javac.html).

**Comment by jwmelto** [comment]
Thanks. That helped me trace the issue down to an unset LANG environment variable.
