### ISSUE TITLE
FAQ webpage doesn't render headings correctly

### ISSUE THREAD

**Issue by breun** [apache/logging-log4j2#1466]
## Description

Some headings on https://logging.apache.org/log4j/2.x/faq.html seem to get rendered incorrectly. For instance, I see `#### How do I specify the configuration file location?` rendered as regular text instead of `How do I specify the configuration file location?` rendered as heading.

**Comment by Chealer** [comment]
Thank you for reporting, but this is already tracked in [LOG4J2-3510](https://issues.apache.org/jira/browse/LOG4J2-3510).

**Comment by breun** [comment]
Ah ok, thanks, I’ll close this one then.
