### ISSUE TITLE
Revamp the manual introduction

### ISSUE THREAD

**Issue by Chealer** [apache/logging-log4j2#1468]
[The manual's introduction page](https://logging.apache.org/log4j/2.x/manual/index.html) mostly consists of a _Log4j 2_ section. That section is somewhat long for an introduction, and it could be confusing. This ticket reports a few close issues:

1. The paragraph initially seems to suggest that Log4j 1 is still maintained, saying "However, through the years development on it has slowed down."
2. The paragraph implies that SLF4J+Logback and Log4j 2 are the only alternatives to Log4j 1, when several other logging frameworks (including Reload4j) exist.
3. It is not clear what the list contains. It appears to be a comparison with both Log4j 1 and SLF4J+Logback. For example, it is unclear if "Support for custom log levels" is a benefit when compared to Log4j 1 only, SLF4J+Logback too, or even just the latter.
4. The reasons for putting so much emphasis on a comparison with Log4j 1 are unclear, or even just outdated. It would be good to indicate that Log4j 1 has known vulnerabilities, but beyond that, I don't see why such an in-depth comparison would warrant inclusion in the introduction at this point.

I don't have a clear solution to propose, but I would first recommend to retitle the section "Log4j 1 and SLF4J+Logback" and reevaluate how prominent a comparison with Log4j 1 should remain. Another option would be to use a comparison matrix rather than a list.

**Comment by rgoers** [comment]
For reference, I expect the intro page was written for 2.0 and we have added new items to the list over time but never reviewed the page. At this point we should remove the references to Log4j 1.x since it has now been 8 years since we stopped supporting it.

**Comment by vy** [comment]
- Make it crystal clear api-vs-implementation
- Link to the API page
- Link to the Concepts page

**Comment by grobmeier** [comment]
Port to 3.x: ca978bfcc71ee8303bd7c0e32ce44257a22515dc
