### ISSUE TITLE
Website: Manual should be more prominent in left sidebar

### ISSUE THREAD

**Issue by Chealer** [apache/logging-log4j2#1469]
It took me a while to find [the website's _API Separation_ page](https://logging.apache.org/log4j/2.x/manual/api-separation.html) today. In hindsight, this is understandable since less important things come higher in the sidebar to the left.

It may be difficult to fully sort the sidebar's elements by importance, but I believe it can easily be improved. Specifically, while facilitating contributions is critical, the manual should surely be above the _FOR CONTRIBUTORS_ section.
![Log4j – API Separation](https://user-images.githubusercontent.com/486141/236549295-3d4992ac-ba94-4f27-8388-b5e96b5f7096.png)

**Comment by rgoers** [comment]
The team has debated this for quite some time. At least one PMC member wants to rewrite the whole manual from scratch. Personally, I think the technology we are using causes the majority of the problems.

**Comment by grobmeier** [comment]
In the meantime, we could actually move the contributors section down.
I also moved Javadoc, Runtime Deps, Support and Thanks to the "Project Information" section, as I don't think this is relevant except for a few.
![image](https://github.com/apache/logging-log4j2/assets/873786/e6899566-9a7e-4485-af93-742e11a1b974)

**Comment by vy** [comment]
Fixed by several changes implemented for #2535.

**Comment by Chealer** [comment]
I (still) think that the manual should be sorted before the _Support_ and _Articles and Tutorials_ pages, but I agree that this is mostly solved.
Thanks @vy
