### ISSUE TITLE
log4j-api: Incomplete/unclear description (simple implementation)

### ISSUE THREAD

**Issue by Chealer** [apache/logging-log4j2#1474]
log4j-api [has the following name and description](https://github.com/apache/logging-log4j2/blob/2.x/log4j-api/pom.xml#LL27C1-L28C50):
```
  <name>Apache Log4j API</name>
  <description>The Apache Log4j API</description>
```

This is at least incomplete, as shown by [this discussion](https://stackoverflow.com/a/76159299/5405434). Log4j developer Piotr P. Karwasz indicates that log4j-api provides a simple Log4j provider, [SimpleLogger](https://github.com/apache/logging-log4j2/tree/2.x/log4j-api/src/main/java/org/apache/logging/log4j/simple). I did not verify that and it is pretty much undocumented, but it is reportedly equivalent to slf4j-simple, except for being built in log4j-api.

I know little about Log4j, but considering that, I suggest replacing log4j-api's description with the following would make it much more complete/accurate:

> Apache Log4j's logging facade API specification. A simple implementation (SimpleLogger) is built-in.

**Comment by rgoers** [comment]
Why? I read the discussion and I doubt that the name and the description in the pom.xml are going to make any difference to anyone who cares.

What would really help is completely separating the documentation for Log4j-API from the documentation for the rest of Log4j.

**Comment by vy** [comment]
@Chealer, thanks so much for the report. Fixed in 5a0262db1293d63ce786ca84839c4cfb5f16c766. We will improve the situation further in:
- #2509
- #2508
- #2535

**Comment by Chealer** [comment]
Thanks to you @vy 
I commented the change and would suggest a small tuning:

> This package contains 2 components of the Apache Log4j project's API, through which applications and libraries can log:
> * its specification
> * and its simple built-in implementation (`SimpleLogger`) for trivial use cases. A fully-fledged implementation, such as Log4j Core, should be preferred for production applications.

**Comment by vy** [comment]
[I think the current state is good enough. We better spend our effort elsewhere.](https://github.com/apache/logging-log4j2/issues/1475#issuecomment-2082010667)
