### ISSUE TITLE
log4j-core: Name/description not so clear

### ISSUE THREAD

**Issue by Chealer** [apache/logging-log4j2#1475]
log4j-core [has the following name and description](https://github.com/apache/logging-log4j2/blob/2.x/log4j-core/pom.xml#LL27C1-L28C61):
```
  <name>Apache Log4j Core</name>
  <description>The Apache Log4j Implementation</description>
```

Software products often call a component _core_ when that component is essential to all other components. This pattern can be seen in numerous Debian packages, notably in the nginx source package, which generates binary packages nginx-core and [nginx-full](https://packages.debian.org/bullseye/nginx-full), the latter depending on the former.

My understanding is that this is not really the case with Log4j Core, since log4j-api does not _need_ log4j-core, which means its name could be misleading (I believe it did confuse me for one). I would therefore recommend setting a name and a description as clear as possible, focusing on "implementation" rather than "core".

I would suggest the following, but this comes from someone who is not knowledgeable about either Log4j or its ecosystem. My suggestion is based on my understanding that "core" means "core of the implementation" but considering that [the API Separation page](https://logging.apache.org/log4j/2.x/manual/api-separation.html) refers repeatedly to the "core implementation", that may be wrong.
```
  <name>Apache Log4j Implementation Core</name>
  <description>Core of Apache Log4j's reference implementation of the Log4j facade API. This implementation provides a full-featured logging library which can also serve as a Simple Logging Facade for Java (SLF4J) provider or as a logging implementation of another logging API.</description>
```

**Comment by rgoers** [comment]
Log4j API is the interface applications code to and will use its built in SimpleLogger implementation if none is provided, but that implementation is too simplistic for the vast majority of users.

Log4j Core is the implementation of the API. It is really the only dependency you need to perform logging for a large portion of the Log4j user base. All the other components are add-on functionality that provides enhancements for special use cases.

As such, I don't really see anything wrong with its name.  Calling it the "implementation core" is misleading as it gives the impression that something else might be required. Log4j Core also cannot act as a provider for SLF4J by itself. It requires for log4j-slf4j-impl or log4j-sfl4j2-impl and log4j-api to do that.

I'm inclined to close this as I don't see how it provides any benefit.

**Comment by Chealer** [comment]
@rgoers this was not just about the name, but you are right about the name. My suggestion was wrong. The name should either be left alone or removed. I suggest to seriously consider removal, since while the name may be correct, it makes no sense to me to have a proper noun in the name but not even use it one in the description.

**Comment by Chealer** [comment]
My pleasure @vy, thank you very much for this great improvement. Here is a suggestion based on your version:

> This package contains the core of the Log4j API's reference implementation. That implementation provides an industrial-grade and versatile library bundling a rich set of components to assist various logging use cases and environments. It notably allows:
> * writing to files, network sockets and databases and sending emails;
> * formatting output as CSV, HTML, JSON, etc;
> * event filtering, which can be configured using frequency, time, regular expressions, scripts, etc.
>     
> While this implementation contains other packages extending this one, the core alone generally suffices. It also contains several extension points to introduce custom components, if needed.

I left Syslog out because I believe it's a protocol, but I don't know much about it, so feel free to re-add it.

**Comment by Chealer** [comment]
@rgoers I am sorry for replying so late. Thank you for your reply.

> As such, I don't really see anything wrong with its name. Calling it the "implementation core" is misleading as it gives the impression that something else might be required.

The issue is non-trivial and I have limited capacity to advise (I haven't worked with Log4j at all this year), but if my understanding is correct, something else *might indeed* be required in some cases, although that depends on how "require" is defined. If logging to MongoDB is considered _required_ in some contexts, then such users do _require_ log4j-mongodb.

I cannot make sense of the name "core" if it isn't for these extensions. I guess the fundamental problem here is that the meaning of "core" is not documented anywhere.

Once that's done, it should also be verified that the terminology is coherent. For example, if log4j-mongodb is considered as part of the RI, then [the MongoDB appender's documentation](https://logging.apache.org/log4j/2.x/log4j-mongodb4.html) shouldn't state that "The MongoDB Appender is dependent on the Log4j 2 API and implementation". It should rather say it depends on the implementation's **core**.

That being said, my suggestion to change the name element was wrong. Unless the project itself is renamed, the name should stay as it is. I guess I was confusing the name field with a short description, but I see that the POM (version 4) doesn't support distinguishing between short and extended descriptions. Sorry about that

**Comment by ppkarwasz** [comment]
> I cannot make sense of the name "core" if it isn't for these extensions. I guess the fundamental problem here is that the meaning of "core" is not documented anywhere.

As far as I understand `log4j-core` was named after `logback-core`. We discussed renaming it many times (e.g. [in this thread](https://lists.apache.org/thread/g71gpqwrhdh8p318flvo9ldsyqbc3fs4)), but we never reached a consensus.

Personally I use "Log4j Core" as name of the reference implementation.

**Comment by Chealer** [comment]
Thank you very much for all this information as well as for starting that most interesting, albeit unfortunate thread @ppkarwasz . It's a shame if renaming the artifact identifier is so challenging in this case, but I think @jvz's suggestion to change the actual name should be considered.

I recommend to either:

1. rename
2. or document what "Log4j Core"/log4j-core is...
    1. and probably remove the name element from the POM

**Comment by Chealer** [comment]
Of course @vy 
The above was not saying that documentation should be in `pom.xml`. It can be documented in there, but for sure it is more important to document on the website.

`pom.xml`'s description does dig into a few details though, so if the definition of Log4j Core is short, it would make a lot of sense to put it there.
