### ISSUE TITLE
JsonTemplateLayout Docs with wrong keyname appender.console.json.

### ISSUE THREAD

**Issue by ghost** [apache/logging-log4j2#1479]
I think here in the examples for JsonTemplateLayout
https://github.com/apache/logging-log4j2/blob/5cc765d77daa68260dbbf79b6b2c0799d32f12bc/src/site/asciidoc/manual/json-template-layout.adoc.vm#L121-L122 the key name should be `.layout.` instead of `.json.`

```properties
appender.console.layout.type = JsonTemplateLayout
appender.console.layout.eventTemplateUri = classpath:EcsLayout.json
```

**Comment by ppkarwasz** [comment]
@robert-gdv,

Thank you for your report. Actually the key used for a layout can be **arbitrary** (e.g. `!@#$%^&*()`) as long as it does not contain a dot `.` character.

When binding configuration values to JavaBean properties, Log4j:

 * binds simple properties (`int`, `String`, etc.) **by name**. Therefore you **need** to use the `target` key to specify the target of a console appender,
 * binds complex properties **by type**. That is why `appender.console.!@#$%^&*().type = JsonTemplateLayout` will work without any problems.

**Comment by robert-gdv** [comment]
Hmm... reviewing the docs:
In https://logging.apache.org/log4j/2.x/manual/appenders.html#consoleappender a parameter layout is described. How does the property parser know, that `appender.console.!@#$%^&*().type` describes a layout?
