### ISSUE TITLE
LevelRangeFilter not working properly with INFO set as minLevel

### ISSUE THREAD

**Issue by NA-Dev** [apache/logging-log4j2#1495]
## Description
I have an appender with a LevelRangeFilter. If I set minLevel="ERROR" it works properly logging only ERROR and above. If I instead set minLevel="INFO" nothing logs at all. If I remove the LevelRangeFilter line altogether, it logs every level properly. So there is some bug with the LevelRangeFilter going on here.

## Configuration

**Version:** [Log4j version] 2.20.0

**Operating system:** [OS and version] Windows 10 and Ubuntu 22.04

**JDK:** [JDK distribution and version] JDK 16.0.1

## Logs

No log4j errors log and it is using my config file properly other than this bug

## Reproduction
Here is my config file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<Configuration status="WARN" monitorInterval="30">
	<Properties>
		<Property name="logger_path" value="log" />
		<Property name="pattern" value="%d{yyyy-MM-dd HH:mm} [%highlight{%-6level}{FATAL=bg_red, ERROR=red, WARN=yellow, INFO=white, DEBUG=cyan}] %C{-3}: %M (%F:%L) - %m%n" />
		<Property name="pattern_teams" value="${hostName}: [%level] %C{-3}: %M (%F:%L) BEGIN_MESSAGE %m BEGIN_EXCEPTION %ex" />
	</Properties>
	<ThresholdFilter level="debug"/>
    <Appenders>
	    <Console name="Console" target="SYSTEM_OUT" follow="true" ignoreExceptions="false">           
	         <PatternLayout pattern="${pattern}%ex" disableAnsi="false"/>
        </Console> 
 
        <RollingFile name="MyLog" fileName="${logger_path}/${hostName}_java_errors.log" filePattern="${logger_path}/$${date:yyyy-MM}/${hostName}_java_errors_%d{MM-dd-yyyy}-%i.log.gz" ignoreExceptions="false" >
            <PatternLayout pattern="${pattern}%ex" disableAnsi="true" />
            <Filters>
	            <LevelRangeFilter minLevel="INFO"/>      
	            <BurstFilter rate="1" maxBurst="3"/>
	        </Filters>
	        <Policies>
	      		<TimeBasedTriggeringPolicy />            
	      		<SizeBasedTriggeringPolicy size="250 MB"/> 
  		    </Policies>
  		    <DefaultRolloverStrategy max="20"/>
        </RollingFile>
 	</Appenders>
 	
    <Loggers>     
        <Root level="info">
	        <AppenderRef ref="Console"/>
            <AppenderRef ref="MyLog"/>
        </Root>
    </Loggers>
    
</Configuration>
```

**Comment by vy** [comment]
Integral values of the (standard) Log4j levels are as follows:

100 – `FATAL`
200 – `ERROR`
300 – `WARN`
400 – `INFO`
500 – `DEBUG`
600 – `TRACE`

(See `Level` and `StandardLevel` classes for details.)

Hence, your `LevelRangeFilter` configuration should be as follows:

`<LevelRangeFilter maxLevel="INFO"/>`

For instance, given the following configuration

```
<Configuration status="ERROR">
  <Appenders>
    <List name="List">
      <LevelRangeFilter maxLevel="INFO"/>
      <PatternLayout pattern="%m%ex"/>
    </List>
  </Appenders>
  <Loggers>
    <Root level="DEBUG">
      <AppenderRef ref="List"/>
    </Root>
  </Loggers>
</Configuration>
```

the below code snippet

```
logger.trace("0");
logger.debug("1");
logger.info("2");
logger.warn("3");
logger.error("4");
````

produces

```
2
3
4
```

I think your issue is misconfiguration, hence I am closing the ticket. Feel free to reopen it if you think otherwise.

**Comment by NA-Dev** [comment]
This is closed in error. I want to log from minLevel INFO to maxLevel FATAL. It is configured correctly and not working.

**Comment by vy** [comment]
Have you tried the following?

```
<LevelRangeFilter maxLevel="INFO" minLevel="FATAL"/>
```

Please note that `minLevel` and `maxLevel` don't do what you have in mind due to integral values associated with them.

**Comment by ppkarwasz** [comment]
I think we can keep this open, since the default values of `minLevel` and `maxLevel` are both `ERROR`. A default value of `OFF` for `minLevel` and `ALL` for `maxLevel` would be more intuitive.

**Comment by NA-Dev** [comment]
Yes, I have tried minLevel INFO and maxLevel FATAL. Nothing logs.

**Comment by ppkarwasz** [comment]
@NA-Dev,

Since `INFO > FATAL`, there is no level between `INFO` and `FATAL`.
Try the configuration proposed by Volkan (`FATAL` as **minLevel** and `INFO` as **maxLevel**).
