### ISSUE TITLE
Update javax dependencies to latest jakarta versions

### ISSUE THREAD

**Issue by mkoncek** [apache/logging-log4j2#1504]
I would like this project to switch to using jakarta dependencies instead of the old javax versions. This would help us get rid of dependencies on old packages in Fedora.

**Comment by mkoncek** [comment]
Sorry I forgot to mention them: I was talking about javax/jakarta `activation` and `mail`.

**Comment by ppkarwasz** [comment]
@mkoncek,

Compiling branch `2.x` is hard. You need to set `JAVA_HOME` to the path of your JDK 8 installation **or** exclude `log4j-jmx-gui` from the build.

The `javax.activation-api` and `javax.mail-api` are required to compile `log4j-core`, but are not required at runtime if you also deploy `log4j-jakarta-smtp`.

**Comment by ppkarwasz** [comment]
I split this issue into #1524, #1526 and #1528.
