### ISSUE TITLE
Reproducibility of `Log4jPlugins.java`

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1520]
The generation of the new plugin cache `Log4jPlugins.java` is non deterministic, which breaks reproducibility of 3.x builds.

As far as I can tell the problem is restricted to the order in which the plugins are declared.

**Comment by rgoers** [comment]
The way it is supposed to work is to find all the plugins in the module and then use the package that they all have in common and then create a plugins package there and add Log4jPlugins.java in that directory. The algorithm should be very deterministic until you add a new plugin that isn't common with the others.

**Comment by jvz** [comment]
Well, this could be fixed fairly easily: alphabetize the entries before writing.

**Comment by jvz** [comment]
Seems to be a regression from LOG4J-2735, but I can't see that issue on Jira for some reason.

**Comment by jvz** [comment]
This is a regression that was otherwise address in 2.x in https://issues.apache.org/jira/browse/LOG4J2-2735

**Comment by jvz** [comment]
Fixed.
