### ISSUE TITLE
Update the JPA appender to Jakarta EE 9

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1526]
In the 3.x version, we should create a `log4j-jakarta-jpa` module that support [Jakarta Persistence 3.0](https://jakarta.ee/specifications/persistence/3.0/), which is part of Jakarta EE 9.

This solves part of #1504.

**Comment by rgoers** [comment]
Can we move all these jee related things to a logging-log4j-jakarta repo? Of course I would expect only the Jakarta related things would be there. I guess we could create a logging-log4j-jee repo for the older stuff.

**Comment by ppkarwasz** [comment]
Sounds good to me.

In that case we should also move `log4j-bom` to its own repo and releasing the modules from one repo will imply releasing a new version of `log4j-bom`.

**Comment by rgoers** [comment]
We would have to think about that. I would think releasing a new version of the BOM would be equivalent to a "Log4j Release".  We may, or may not, want to do that for a release of every sub-component. From an ASF perspective I am not quite sure what should be deployed to the dist location for those kinds of releases. Does the zip contain artifacts from all the repos or just the bom pom.xml?

**Comment by vy** [comment]
I moved the BOM conversation to [this mailing list thread])(https://lists.apache.org/thread/94ogfkr31q87fdlq6d6qh0tflgss0rdo).

**Comment by ppkarwasz** [comment]
I am closing this issue, since `log4j-jpa` has been deprecated: #1951.
