### ISSUE TITLE
Log4jEventBuilder does not support dynamic fqcn so incompatible with slf4j

### ISSUE THREAD

**Issue by oshai** [apache/logging-log4j2#1533]
## Description

In order to allow changing the fqcn (and support other wrapping frameworks like slf4j kotlin-logging) in fluent api that logs line numbers, should make Log4jEventBuilder implement CallerBoundaryAware.

## Configuration

**Version:** 2.20

## Logs

```
LoggingWithLocationTest[jvm] > testNullLoggingWithLocationEntryExitOpt()[jvm] FAILED
    org.opentest4j.AssertionFailedError: expected: <TRACE ClassWithLoggingForLocationTesting.logExitOpt(26) - entry with (1, 2)
    INFO ClassWithLoggingForLocationTesting.logExitOpt(27) - log entry body
    TRACE ClassWithLoggingForLocationTesting.logExitOpt(28) - exit with (null)> but was: <TRACE ClassWithLoggingForLocationTesting.logExitOpt(26) - entry with (1, 2)
    INFO LocationAwareKLogger.at(46) - log entry body
```

## Reproduction

See reproduction here: https://github.com/oshai/kotlin-logging/pull/332/commits/92378ee81547c5bd301eb9d5fd9ef271fb5a1edf

The code switches to fluent api, and the unit test in github actions fails. For example: `LoggingWithLocationTest.testNullLoggingWithLocationEntryExitOpt()` with the output above.

I can add a fix if you'd like.

**Comment by ppkarwasz** [comment]
@oshai,

Thanks for the report. If you submit a PR, we should be able to include it in the next release. The Log4j's equivalent of SLF4J's `CallerBoundaryAware` is [`BridgeAware`](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/BridgeAware.html) and our logger builder implements it.

**Comment by oshai** [comment]
I created a fix here: https://github.com/apache/logging-log4j2/pull/1534

Let me know if my intention is clear.

**Comment by ppkarwasz** [comment]
@oshai, thank You for your contribution.

**Comment by oshai** [comment]
@ppkarwasz Thanks!

Do you know which / when a new version will be released with the fix?

**Comment by ppkarwasz** [comment]
@oshai,

We try to release quarterly, so version 2.20.1 is already overdue. However everything depends on our daily jobs, since the release process requires a lot of time.

**Comment by oshai** [comment]
Thanks!
