### ISSUE TITLE
HighlightConverter does not honor {STYLE_NAME} configuration

### ISSUE THREAD

**Issue by zartc** [apache/logging-log4j2#1545]
## Description

When using the HighlightConverter like this: `%highlight{%5level}{LOGBACK}` the HighlightConverter always uses the colors of the DEFAULT preset instead of the color of the LOGBACK as asked.

## Configuration

**Version:** 2.20.0

**Operating system:** Windows 10

**JDK:** temirun-11

## Logs

none

## Reproduction

Configure a converter with: `%highlight{%5level}{LOGBACK}`
You will discover that the HighlightConverter always uses the colors of the DEFAULT preset.

## Fixe

`HighlightConverter.createLevelStyleMap()` method is missing a check at line 151 to see if the passed `options[1]` contains a map of LEVEL=color or a preset style name.

```java
if (!string.contains("=")) {
    return STYLES.getOrDefault(string, DEFAULT_STYLES);
}
```

**Comment by ppkarwasz** [comment]
Hi @zartc,

As [documented](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout) the correct syntax is:
```
%highlight{%5level}{STYLE=LOGBACK}
```

I wouldn't complexify the syntax to accept just "LOGBACK". There should be probably a warning if a user employs an incorrect syntax (without `=`). Could you submit a PR with the warning?

**Comment by aawad6** [comment]
If @zartc doesn't mind, I can add the necessary warning message.

**Comment by ppkarwasz** [comment]
@aawad6, go ahead!

**Comment by vy** [comment]
@zartc, thanks so much for the report! :bow: The issue is fixed. It will be available with the next release.
