### ISSUE TITLE
in log4j2 version 2.17.1 unable to have the current log name suffixed with current date

### ISSUE THREAD

**Issue by testcloud2023** [apache/logging-log4j2#1561]
I am using log4j2 version 2.17.1 and I am unable to have with this setting in log4j.xml :

            <RollingFile name="EVENT_LOG_FILE" fileName="${path}/kpi/${logNamePrefix}_events-${date:yyyy-MM-dd}.log"
                        filePattern="${path}/kpi/${logNamePrefix}_events-%d{yyyy-MM-dd}.log">
                <Policies>
                    <TimeBasedTriggeringPolicy/>
                </Policies>
                <PatternLayout pattern="TSL=%d{yyyyMMdd:HH:mm:ss.SS'Z'},%m%n" />
            </RollingFile>
the current date file named with the current date.

Example for a file generated today : Jul 17th 2023

Current : the filename is incorrectly named with this suffix : 2023-07-07

rw-rr-. 1 owner group  12345 Jul  17 08:30 prefix_events-2023-07-07.log
Expected : the suffix must be 2023-07-17

rw-rr-. 1 owner group  12345 Jul  17 08:30 prefix_events-2023-07-17.log
Observation : 2023-07-07 seems to be the name of the oldest file available

P.S. I don't need to have any rolling policy nor any compression happening on my log file if that can help address the issue

**Comment by rgoers** [comment]
Please try with the latest release. This sounds like something I may have fixed in a recent release.

**Comment by testcloud2023** [comment]
Thanks rgoers for your comment, would you have a JIRA or a reference about the fix ?

**Comment by ppkarwasz** [comment]
Sorry, I thought this was posted on `log4j-user`.

As clearly stated in [our support policy](https://logging.apache.org/log4j/2.x/support.html), please **don't use GitHub Issues for questions**.
