### ISSUE TITLE
Build: Make Apache RAT ignore Eclipse configuration files

### ISSUE THREAD

**Issue by magicwerk** [apache/logging-log4j2#1580]
Build fails if project has been opened with Eclipse which creates project files which make RAT failing the build.
The pom.xml currently only has excludes for IntelllJ, add those for Eclipse as well, e.g.
```
<!-- Eclipse files -->
<exclude>**/*.project</exclude>
<exclude>**/*.classpath</exclude>
<exclude>**/*.prefs</exclude>
```

**Comment by ppkarwasz** [comment]
The Apache RAT plugin has some [implicit excludes](https://github.com/apache/creadur-rat/blob/master/apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ExclusionHelper.java), which cover both Eclipse and Intellij IDEA.

What probably happens in your case is that by switching between the `2.x` and `main` branch the list of Maven modules changes, the source code disappears, but the Eclipse files remain. E.g. if you imported `log4j-api-java9` and `log4j-core-java9` into Eclipse, by switching from `2.x` to `main` those folders will be empty directories with only Eclipse files. Just delete those projects and the data on disk and you'll be fine.

**Comment by magicwerk** [comment]
You're fully right, that was the problem.
