### ISSUE TITLE
Unable to send query to Mailing List log4j-user@logging.apache.org

### ISSUE THREAD

**Issue by danishmarif** [apache/logging-log4j2#1620]
Hi, 
I'm trying to understand a scenario and as per documentation and recommendation I tried to email to the Mailing list **log4j-user@logging.apache.org** which returns unsuccessfully.

Following is the response I get when I email. 

**Hi. This is the qmail-send program at [apache.org](http://apache.org/).
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<[log4j-user@logging.apache.org](mailto:log4j-user@logging.apache.org)>:
Must be sent from an @[apache.org](http://apache.org/) address or a subscriber address or an address in LDAP.**

Can anyone guide how can I ask my query and through which platform?

**Comment by vy** [comment]
@danishmarif, these are mailing lists. You first need to subscribe and then post your questions. Otherwise, you cannot see the answers to your question.
