### ISSUE TITLE
Cant't configure Syslog to write stack trace correctly with RFC 5424 standart

### ISSUE THREAD

**Issue by fractal3000** [apache/logging-log4j2#1674]
Hi, dear Log4j authors!

Please, could you explain, how to configure Syslog appender that is able to write stack trace message in "message" part of RFC5424 format?

Documenation doesn't give any comrehensive example.

We couldn't find any working example.

We use 2.20.0 version of log4j2 library.
We tried to use this configuration for appender 

        <Syslog name="syslog" format="RFC5424" host="<some IP>" port="514" protocol="UDP" newLine="true" includeMDC="true">
            <LoggerFields>
                <KeyValuePair key="thread" value="%t"/>
                <KeyValuePair key="priority" value="%p"/>
                <KeyValuePair key="category" value="%c"/>
                <KeyValuePair key="exception" value="%ex{full}"/>
            </LoggerFields>
        </Syslog>

Is it possible that it is a bug or it is an our mistake?

Thanks in advance, Pavel.

**Comment by vy** [comment]
Hey @fractal3000!

_[As indicated in [the Log4j support policy](https://logging.apache.org/log4j/2.x/support.html#discussions), please use `log4j-user@logging.apache.org` for questions next time.]_

Your configuration works just fine for me. My test `log4j2.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="OFF">
  <Appenders>
    <Syslog name="syslog" format="RFC5424" host="127.0.0.1" port="51400" protocol="UDP" newLine="true" includeMDC="true">
      <LoggerFields>
        <KeyValuePair key="thread" value="%t"/>
        <KeyValuePair key="priority" value="%p"/>
        <KeyValuePair key="category" value="%c"/>
        <KeyValuePair key="exception" value="%ex{full}"/>
      </LoggerFields>
    </Syslog>
  </Appenders>
  <Loggers>
    <Root level="trace">
      <appender-ref ref="syslog"/>
    </Root>
  </Loggers>
</Configuration>
```

And my `nc` output:

```
$ nc -v -u -l 51400
Bound on 0.0.0.0 51400
Connection received on localhost 50429
<134>1 2023-08-16T22:06:03.290+02:00 tahta /home/vy/Projects/log4j/2/log4j-layout-template-json-test/target/test-classes/syslog.xml 845631 - [mdc@32473 category="org.apache.logging.log4j.layout.template.json.SyslogTest" exception="" priority="INFO" thread="main"] foo
<134>1 2023-08-16T22:06:03.296+02:00 tahta /home/vy/Projects/log4j/2/log4j-layout-template-json-test/target/test-classes/syslog.xml 845631 - [mdc@32473 category="org.apache.logging.log4j.layout.template.json.SyslogTest" exception="" priority="INFO" thread="main"] bar
```

**Comment by fractal3000** [comment]
Hi, Volkan!
Thanks a lot for your answer!
But I see the problem in your log that you have sent.
 
The «exeption» parameter in your log messages is empty.
<134>1 2023-08-16T22:06:03.290+02:00 tahta /home/vy/Projects/log4j/2/log4j-layout-template-json-test/target/test-classes/syslog.xml 845631 - ***@***.*** category="org.apache.logging.log4j.layout.template.json.SyslogTest" exception="" priority="INFO" thread="main"] foo
 
And this was the main problem — to show exception stack trace in log.
Will be thankfull if you can comment this problem.
 
Thank in advance, Pavel Aleksandrov.
 
--
Павел Александров

**Comment by vy** [comment]
Using the example Log4j configuration I shared, the following command:

```
logger.info("dumping", new Exception());
```

yields to the following output in `nc`:

```
<134>1 2023-08-25T09:23:16.117+02:00 tahta /home/vy/.../syslog.xml 1101098 - [mdc@32473 category="bar" exception="java.lang.Exception
	at org.apache.logging.log4j.layout.template.json.JsonTemplateLayoutAdditionalFieldTest.foo(JsonTemplateLayoutAdditionalFieldTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	...
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
" priority="INFO" thread="main"] dumping
```

Hence, the stack trace gets attached to the `exception` field of the log entry. Would you mind explaining (preferably, even showing an example of) what were you expecting instead, please?
