### ISSUE TITLE
Documentation mismatch regarding Lookups

### ISSUE THREAD

**Issue by yakovsh** [apache/logging-log4j2#1675]
## Description
There is a mismatch in documentation between the two pages on lookups:
https://logging.apache.org/log4j/2.x/manual/lookups.html
https://logging.apache.org/log4j/2.x/manual/configuration.html#PropertySubstitution

Additionally, the list of available lookups in both places doesn't match up with code. For example, the "base64" lookup is in code for the 2.xx version, and the "bundle" lookup doesn't appear on the lookups doc page, but only in the configuration doc page. Third, the table in the configuration page doesn't list all available lookups that appear in code and on the lookups page.

I can put together a pull request with changes for the documentation if desired.

P.S. Previous bug report regarding similar issue here:
https://issues.apache.org/jira/browse/LOG4J2-3504

**Comment by rgoers** [comment]
PRs are very welcome!

**Comment by vy** [comment]
#1681 is merged.
