### ISSUE TITLE
JsonTemplateLayout does not override the requiresLocation method

### ISSUE THREAD

**Issue by jalynxing** [apache/logging-log4j2#1692]
`JsonTemplateLayout` does not implements `LocationAware` and override `requiresLocation`, making `LoggerConfig::requiresLocation` always return false and `AbstractLogger::getLocation(fqcn)` return null. This results in the location not being passed to its underlying appenders when needed.
Instead, `JsonTemplateLayout::requiresLocation` should return true when any of its appenders requires a location.

**Comment by vy** [comment]
Thanks for the report @jalynxing! :heart_eyes: Fixed in 613b27a6f520309de16b47ba59527ef76476282d.
