### ISSUE TITLE
[MS5] SBOM Support & Security

### ISSUE THREAD

**Issue by grobmeier** [apache/logging-log4j2#1707]
This milestone aims to harden Log4j and its satellite projects ([`logging-parent`](/apache/logging-parent), [`log4j-tools`](/apache/logging-log4j-tools), [`log4j-scala`](/apache/logging-log4j-scala), etc.) against software supply chain attacks. Implementation tasks are detailed below.

## Consult to security experts

We had meeting with [Kamal Kothyari](https://www.linkedin.com/in/kamko) on 2023-10-13. Discussion topics and action points are as follows:
* The current distribution model (Nexus, Maven Central, ASF archive, etc.)
  * ✔ Matches the industry standards, no improvement points
  * ✔ We implemented [reproducible builds](https://reproducible-builds.org/) in #1777 and #1780
* The current security support and vulnerability disclosure model of Log4j
  * ✔ Overhauling [the Log4j security page](https://logging.apache.org/log4j/2.x/) to provide better guidance and up to date information (#1948)
  * ✔ [Private communication channels for security-related discussions](https://logging.apache.org/log4j/2.x/support.html#maintainer_discussions)
  * ✔ [CVE lists](https://logging.apache.org/log4j/2.x/security.html)
  * Project activity status (active, inactive, etc.)
    * It has been stated that it is crucial to be transparent about the project status. Is it actively maintained? Is it dormant? Is it unmaintained? etc.
    * We have been discussing to move more or less inactive projects to a dormant state; this discussion is on-going.
    * ✔ We set up [a page to monitor the activity status of all Apache Logging Services projects](https://logging-activity-monitor.staged.apache.org/). This increases our transparency and helps users to give well-informed decisions on unmaintained projects.

## Software Bill of Materials (SBOM)

SBOMs are crucial in determining the impact surface of software against vulnerabilities. They capture an inventory of software components and services and their dependency relationships. This is essential for risk identification in the face of software supply chain attacks.

Our research yielded that there are two industry standards for SBOM specification in the market:
* [CycloneDX SBOM](https://cyclonedx.org/capabilities/sbom/)
* [SPDX](https://spdx.dev/)

[An extensive comparison of both alternatives](https://blog.sonatype.com/comparing-sbom-standards-spdx-vs.-cyclonedx-vs.-swid) is published by Sonatype, the company behind Maven Central, Nexus, etc. According to our understanding, both standards are well-established and feature-rich. That said, SPDX is more focused on license compliance, whereas CycloneDX is on more component identity. We decided to proceed with CycloneDX.

We had several discussions with @hboutemy (a member of [`cyclonedx-maven-plugin`](https://github.com/CycloneDX/cyclonedx-maven-plugin/commits/master) maintainers and Apache Maven PMC) and @stevespringett (creator of [DependencyTrack](https://github.com/DependencyTrack) and the chair of CycloneDX SBOM standard) and also a video call on 2023-11-03. They generously helped us to clarify various implementation details. This work resulted in several improvements to the existing tooling too;
- CycloneDX/cyclonedx-maven-plugin#409
- CycloneDX/cyclonedx-maven-plugin#245
- CycloneDX/cyclonedx-maven-plugin#414
- CycloneDX/cyclonedx-maven-plugin#416
- CycloneDX/cyclonedx-maven-plugin#420
- CycloneDX/cyclonedx-maven-plugin#421
- CycloneDX/cyclonedx-maven-plugin#425
- CycloneDX/cyclonedx-maven-plugin#428

Implemented Log4j-related tasks:

- [x] Implement a CycloneDX baseline for all Maven-based Apache Logging Services projects (apache/logging-parent@ebc246f4d974afb34a507967c4f831ca34fc8333, apache/logging-parent@954f7f22cff863b30887f0acf98a9a49267c98ee)
- [x] Enhance the SBOM for Logging Parent (apache/logging-parent@fc8fd366f29d8d199f2801085c10fe4df277aee1)
- [x] Enhance the SBOM for Log4j (ee9c39b3f646e9b289127041ceb27dbb7da8b7ea)
- [x] Enhance the SBOM for Log4j Tools (apache/logging-log4j-tools@cd5dc8ebff4f879cf206880448ac144127b2ab8c)
- [x] Enhance the SBOM for Log4j Transform (apache/logging-log4j-transform@703bdc2fe789264b7b4410431845dfe16c9d8b92)
- [x] Enhance the SBOM for Log4j Scala (apache/logging-log4j-scala@b38e008021da717577c59cafcadcbe7b2417a653)
- [x] Enhance the SBOM for Log4j Kotlin (apache/logging-log4j-kotlin@eab4c2095e10c1062c0b7316334f17a821acb4c1)
- [x] Enhance the SBOM for Log4j JMX GUI (apache/logging-log4j-jmx-gui@139dcd7f7ec4b89534aaba7ae1786eae4ae3173e)

### Where is SBOM?

SBOM is streamlined by `logging-parent`, and hence its complete documentation is accessible in [its website](https://logging.apache.org/logging-parent/latest/#cyclonedx-sbom). In a nutshell, all deployed Maven artifacts are accompanied by a CycloneDX SBOM file. (For example, see [this `sbom.xml` from `log4j-api`](https://repository.apache.org/content/groups/snapshots/org/apache/logging/log4j/log4j-api/2.22.0-SNAPSHOT/log4j-api-2.22.0-20231107.143949-28-cyclonedx.xml).) Produced SBOMs are enriched with `vulnerability-assertion` references to a [CycloneDX Vulnerability Disclosure Report (VDR)](https://cyclonedx.org/capabilities/vdr) that Apache Logging Services uses for all projects it maintains. This VDR is accessible through the following URL: https://logging.apache.org/cyclonedx/vdr.xml To the best of our knowledge, Apache Logging Services is **the very first ASF project that has ever published a VDR file!**

## Static code analysis

In #1705 and #1706, we integrated various static code analysis tools into the code base. In this milestone, we reviewed security-related findings from generated reports.

- [x] Review CodeQL report (it is privately accessible from [here](/apache/logging-log4j2/security/code-scanning), we checked all)
- [x] Review Spotbugs report (#1921)
- [x] Review Error Prone report (#1961)

## Transparent communication for users

Indirectly related to security, we have added an "Activity Monitor" to showcase the activity of our modules. All commits related to the activity monitor can be found in a separate branch: 
https://github.com/apache/logging-site/commits/activity-monitor

In addition to better communication, we had to improve the website structure and now use Jekyll as our main website-building system for faster turnaround.

**Comment by ppkarwasz** [comment]
The problem with the `distribution` link was reported in CycloneDX/cyclonedx-maven-plugin#245

**Comment by ppkarwasz** [comment]
We should also consider including a [VEX](https://cyclonedx.org/capabilities/vex/) and/or [VDR](https://cyclonedx.org/capabilities/vdr/) report.

These could double the information we already provided in the Github "Security" tab. For example we could dismiss:

- [Apache Cassandra: Privilege escalation when enabling FQL/Audit logs](https://github.com/apache/logging-log4j2/security/dependabot/48),
- [Improper Access Control in SLF4J](https://github.com/apache/logging-log4j2/security/dependabot/26) caused by the usage of SLF4J Ext 1.7.25 (before the breaking change in 1.7.26). @rgoers, do we still need to support `org.slf4j.ext.EventData` or can we drop the feature?
- [Guava vulnerable to insecure use of temporary directory](https://github.com/apache/logging-log4j2/security/dependabot/37). Cassandra is holding back our Guava version: it can not work with Guava higher than 25.x or so.

**Comment by grobmeier** [comment]
Related to website improvements:
https://github.com/apache/logging-site/commit/eff1c9a6f893d023b8d594a034d3c479262d1fbf
https://github.com/apache/logging-site/commit/6aab16de13bef0533f130eb159b5af0dd9e85082
https://github.com/apache/logging-site/commit/19074839c1babf04c75e6a1657bb78b652da838c
https://github.com/apache/logging-site/commit/bf902d8743c71dded40e4e92af67635a1247717b
https://github.com/apache/logging-site/commit/caa65e33ed4b93d03c905d10bef4612a1608de72
https://github.com/apache/logging-site/commit/40e6432308b3dbccd04f704eaf1e10175d5ae3a6
among others.
