### ISSUE TITLE
Keep consistent signing key for releases

### ISSUE THREAD

**Issue by liutikas** [apache/logging-log4j2#1734]
`org.apache.logging` maven group has had at least 3 signing keys:
- https://keyserver.ubuntu.com/pks/lookup?search=0x9d0a56aaa0d60e0c0c7dccc0b4c70893b62babe8&fingerprint=on&op=index
- https://keyserver.ubuntu.com/pks/lookup?search=0xca62ed130e4053944406df640181b45ea58677bc&fingerprint=on&op=index
- https://keyserver.ubuntu.com/pks/lookup?search=0x8378bfaad82fe5aa602ac356031ee010ca15d1ee&fingerprint=on&op=index

they all seem to belong to mattsicker@apache.org

It would be great if the key would not change from version to version, as that means we have to keep updating our allowlist when we do signature validation.

**Comment by ppkarwasz** [comment]
@liutikas,

You can find all our keys on: https://dist.apache.org/repos/dist/release/logging/KEYS
All these people are allowed to prepare and sign a release. The redundancy is for security reasons: if a committer is not available to perform a release, another one can do it.

@jvz has two main keys:
 * a 4096 bit RSA key with fingerprint `748F 15B2 CF9B A8F0 2415  5E6E D7C9 2B70 FA1C 814D`,
 * an Ed25519 key with fingerprint `8378 BFAA D82F E5AA 602A  C356 031E E010 CA15 D1EE`

You should trust these keys and **all** the signing subkeys present or future signed by these keys.

**Comment by vy** [comment]
@ppkarwasz is right. The good news is, we are actively working on migrating all Log4j et al. releases to CI (GitHub Actions) and there the signing operation will always be performed using the very same key: the one associated with `private@logging.apache.org` in [KEYS](https://dist.apache.org/repos/dist/release/logging/KEYS).

Note that even in the best case – i.e., one key is used always, everywhere – they key might get compromised. That would require us to revoke the key, remove it from `KEYS`, and place there a new one. Hence the reality doesn't give much room to a one key to rule them all.

**Comment by vy** [comment]
I am closing this ticket, since this is [how ASF releases operate](https://infra.apache.org/release-signing.html). @liutikas, if you disagree and have a proposal on how to improve this, feel free to reopen the ticket.
