### ISSUE TITLE
Create a reusable release process

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1772]
Since the Log4j project uses multiple repositories, we need to standardize the release process.

To do it we need to:

- [ ] Delegate to the apache/logging-parent `pom.xml` file the responsibility for creating the release distribution, managing release notes, and enforcing QA measures,
- [ ] Create reusable GitHub Actions workflows responsible for building and deploying the distribution.

**Comment by vy** [comment]
This has been completed with [the recent `logging-parent` 10.0.0 release](/apache/logging-parent/releases/tag/rel%2F10.0.0). See [this `log4j-tools` GitHub Actions workflow run](https://github.com/apache/logging-log4j-tools/actions/runs/6120297528) demonstrating a successful release cut using a SNAPSHOT version of this `logging-parent` release. All preparations (release notes, source and binary distributions, vote & announcement emails, etc.) are staged to both Nexus and SVN and waiting the release manager to proceed.
