### ISSUE TITLE
Move Log4j JMX GUI to its own repository

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1773]
Log4j JMX GUI is essentially a separate product like Chainsaw and it shouldn't reside in the main Log4j repo.

It is a Java 8 application that relies on the `jconsole.jar` file that is not available in JDK 9+, hence it blocks the rest of the Maven modules from using a more recent JDK for compilation.

**Comment by vy** [comment]
`log4j-jmx-gui` has been moved to its own repository ([logging-log4j-jmx-gui](/apache/logging-log4j-jmx-gui)) with a fully functional build and CI pipeline.
