### ISSUE TITLE
Align support files

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1775]
All our Java repos should have a similar structure. In particular:

 - Maven Wrappers, `README.adoc`, `LICENSE.txt`, `RELEASING.adoc` should be the same,
 - each repo should have an easy to find pointer to our security policy,
 - each repo should use `log4j-changelog` to provide release notes/change list.

This issue probably concerns all our (non-site) repos:
 - [ ] https://github.com/apache/logging-log4j-audit,
 - [ ] https://github.com/apache/logging-log4j-audit-sample,
 - [ ] https://github.com/apache/logging-log4j-boot,
 - [ ] https://github.com/apache/logging-log4j-jmx-gui,
 - [ ] https://github.com/apache/logging-log4j-kotlin,
 - [ ] https://github.com/apache/logging-log4j-plugins,
 - [ ] https://github.com/apache/logging-log4j-samples,
 - [ ] https://github.com/apache/logging-log4j-scala,
 - [ ] https://github.com/apache/logging-log4j-server,
 - [ ] https://github.com/apache/logging-log4j-tools,
 - [ ] https://github.com/apache/logging-log4j-transform.

**Comment by ppkarwasz** [comment]
We could add a _shared_ Github Action that:

 - takes some resources from the latest release of [Apache Software Foundation Resource Bundles](https://github.com/apache/maven-apache-resources),
  - takes other resources from the Logging parent.

**Comment by vy** [comment]
#1774 carries out a massive facelift operation across all Log4j-related repositories of Apache Logging Services. There the auxiliary support files are updated and aligned for Log4j repositories that are still actively developed:

- [logging-parent](https://github.com/apache/logging-parent)
- [logging-log4j-tools](https://github.com/apache/logging-log4j-tools)
- [logging-log4j-transform](https://github.com/apache/logging-log4j-transform)
- [logging-log4j-kotlin](https://github.com/apache/logging-log4j-kotlin)
- [logging-log4j-jmx-gui](https://github.com/apache/logging-log4j-jmx-gui)
- [logging-log4j-samples](https://github.com/apache/logging-log4j-samples)
