### ISSUE TITLE
Context data is lost if AsyncLogger and AsyncLoggerConfig are both used

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1786]
## Description

If the user uses both an `AsyncLoggerContext` (which makes all loggers to be of type `AsyncLogger`) and `AsyncLoggerConfig`, a race condition can occur, which causes context data to be lost.

## Details

If both `AsyncLogger` and `AsyncLoggerConfig` are used together (which is no advised, but possible and there is a test for it):
 * `AsyncLoggerConfig#log` is called from the main disruptor thread with a `RingBufferLogEvent` argument,
 * `AsyncLoggerConfig` calls `RingBufferLogEvent#createMemento()` before sending the event to its own disruptor thread. However this method does not make a copy of the context data, nor does it mark the data as "frozen",
 * A `RingBufferLogEvent#clear()` on the main disruptor thread clears the context data. If the disruptor thread of `AsyncLoggerConfig` didn't log the message yet, it will log it without context data.

**Comment by ppkarwasz** [comment]
This issues causes the "flakiness" `AsyncLoggerThreadContextCopyOnWriteTest` and related tests from #1568.

As it turns out, the tests were not "flaky", but pointed out a real problem.

**Comment by jvz** [comment]
That's the fun thing about flaky tests; sometimes they flake because they don't assert the right thing, and sometimes they flake because they don't set things up such that what they're asserting is deterministic. Nice find!
