### ISSUE TITLE
Broken Apache Commons Logging bridge in version `2.21.0`

### ISSUE THREAD

**Issue by rbri** [apache/logging-log4j2#1865]
## Description

As part of the HtmlUnit (https://github.com/HtmlUnit/htmlunit) project i have a lot of test cases doing detailed and sometimes strange things to test some functionality.
In this special case i temporary add an appender to check if something happen on the wire.

The code looks like this:

        final Logger logger = (Logger) LogManager.getLogger("org.apache.http.headers");
        final Level oldLevel = logger.getLevel();
        Configurator.setLevel(logger.getName(), Level.DEBUG);

        final StringWriter stringWriter = new StringWriter();
        final PatternLayout layout = PatternLayout.newBuilder().withPattern("%msg%n").build();

        final WriterAppender writerAppender = WriterAppender.newBuilder().setName("writeLogger").setTarget(stringWriter)
                .setLayout(layout).build();
        writerAppender.start();

        logger.addAppender(writerAppender);
        try {
            ((DefaultCredentialsProvider) getWebClient().getCredentialsProvider())
                                            .addCredentials("jetty", "jetty".toCharArray());

            loadPage("Hi There");
            int unauthorizedCount = StringUtils.countMatches(stringWriter.toString(), "HTTP/1.1 401");
            assertEquals(1, unauthorizedCount);
        }
        finally {
            logger.removeAppender(writerAppender);
            Configurator.setLevel(logger.getName(), oldLevel);
        }

This works fine in 2.20.0 and the years before but now with 2.21.0 i fails because there is not output at all - stringWriter.toString() returns an empty string.

Any idea?
Will try to help as much as possible, doing debugging or what else needed to get this working again with the new versions.

Thanks for the great libaray
    
  Ronald

## Configuration

**Version:** 2.21.0

**Operating system:** Win

**JDK:** JDK 11

**Comment by ppkarwasz** [comment]
@rbri,

I am not aware of any changes in `2.21.0` that could change the way this code works. Can you pinpoint the unit tests in [HtmlUnit/htmlunit](https://github.com/HtmlUnit/htmlunit) that fail and how to run them?

**Comment by rbri** [comment]
@ppkarwasz thanks for your fast answer

to reproduce you can do
* get the project - you need jdk 11 to run the tests
* the test is org.htmlunit.DefaultCredentialsProvider2Test.basicAuthentication_singleAuthenticaiton()

If you have any problems you can reach me by mail - ronald dot brill at gebit dot de

**Comment by ppkarwasz** [comment]
@rbri,

The logs you are looking for actually come from the Apache Commons Logging bridge (`log4j-jcl`). In version `2.21.0` we replaced a manually written [`ServiceLoader`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html) file with an automatically generated one to cover both classpath and modulepath usages.

The problem is that JCL does not actually use the `ServiceLoader` (it didn't exist when the mechanism was invented) and it requires a service file **without** comments. I reported this as [`LOGGING-186`](https://issues.apache.org/jira/browse/LOGGING-186).

We need to return to a simplified service file.

**Comment by ppkarwasz** [comment]
There are some workarounds:

1. JCL has many ways to configure a `LogFactory` (that is probably why our tests didn't detect it). For example you can add a `commons-logging.properties` file with content:
   ```
   org.apache.commons.logging.LogFactory = org.apache.logging.log4j.jcl.LogFactoryImpl
   ```
   (I submitted this as HtmlUnit/htmlunit#651)

1. You can replace `commons-logging:commons-logging` with [`org.springframework:spring-jcl`](https://mvnrepository.com/artifact/org.springframework/spring-jcl), which is a **drop-in** replacement for JCL, that logs directly to the Log4j API (hence no need for `log4j-jcl` any more).

**Comment by ppkarwasz** [comment]
@rbri and @LumnitzF,

Due to the relatively high usage of JCL in many libraries, we decided to make a patch release:

https://lists.apache.org/thread/9wsm9v5tlhohrko77hc6mj4lsg0mw9rp

Can you test it and vote on it? The staging repo and instructions are in the `dev` e-mail.

**Comment by rbri** [comment]
@ppkarwasz will test but you have to wait until monday because I'm not in front of the pc right now.
Hope that is ok...

**Comment by ppkarwasz** [comment]
@rbri,

Sure, take your time.

**Comment by LumnitzF** [comment]
I tested the patch and it works for my product :)
Thanks a lot for the fast fix!

**Comment by rbri** [comment]
@ppkarwasz same here - 2.21.1 work!

Again, thanks a lot...
