### ISSUE TITLE
How do I check the version of log4j library version deployed in the Java runtime?

### ISSUE THREAD

**Issue by pantdeepak** [apache/logging-log4j2#1923]
As clearly indicated in [the Log4j support page](https://logging.apache.org/log4j/2.x/support.html#issues), **please use mailing lists for questions!**

Up until version 2.20.0, I was able to use following method to check the version #.
org.apache.logging.log4j.LogManager.class.getPackage().getImplementationVersion()

Starting version 2.21.1 the above method returns null as I could not find "Implementation-Version" entry in the MANIFEST.MF file.

**Comment by vy** [comment]
@pantdeepak, thanks for the report, I am on it.

@rgoers, not by the CI release process, but the newly employed `bnd-maven-plugin`.

**Comment by vy** [comment]
@pantdeepak, Log4j et al. is parented by `logging-parent` and I have fixed the problem there: apache/logging-parent@a43a0b26066b637a5b0cd07cee877c83f0f3347d. `logging-parent` version `10.3.0` is expected to be released next week and promptly its version will be bumped for Log4j et al.

**Comment by pantdeepak** [comment]
Thank you very much for your prompt attention to this issue. Much appreciated.
