### ISSUE TITLE
Remove module/features in `3.x`

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1951]
We should remove the following Maven modules or features in `3.x`:
 
 - [ ] `log4j-cassandra`,
 - [ ] CouchDB appender,
 - [ ] GELF appender,
 - [ ] Kafka appender,
 - [ ] JeroMQ appender,
 - [ ] `log4j-jpa`,
 - [ ] `log4j-mongodb3`,
 - [ ] `log4j-spring-boot`,
 - [ ] Java EE SMTP appender,
 - [ ] `log4j-taglib`,
 - [ ] JsonLayout,
 - [ ] YamlLayout.

**Comment by ppkarwasz** [comment]
The following modules are not deprecated, but they should be removed from the main repo (cf. #1966):

- [ ] `log4j-jakarta-smtp`,
- [ ] `log4j-jakarta-web`,
- [ ] `log4j-jms`,
- [ ] `log4j-smtp`,
- [ ] `log4j-web`.

**Comment by vy** [comment]
This issue is addressed by #1981 and #1985.
