### ISSUE TITLE
Generate reference documentation and XSD from metadata

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1955]
Log4j plugins follow a slightly modified [JavaBean](https://en.wikipedia.org/wiki/JavaBeans) model. As a first step of #1954 we should:

- [x] research the available metadata formats that could be employed to document Log4j plugins,
- [x] choose the most appropriate metadata format based on: maintenance state, available tools and features. An in-house solution should have **lowest** priority (cf. [NIH](https://en.wikipedia.org/wiki/Not_invented_here)),
- [x] use an example metadata file to generate an XSD schema,
- [x] use an example metadata file to generate reference documentation pages.

**Comment by ppkarwasz** [comment]
A loose list of metadata formats we might consider:

- an XML Schema itself,
- a [Plexus component descriptor](https://codehaus-plexus.github.io/guides/developer-guide/configuration/index.html),
- a [Maven plugin descriptor](https://maven.apache.org/ref/3.9.5/maven-plugin-api/plugin.html), which is used by the [Maven Plugin plugin](https://maven.apache.org/plugin-tools/maven-plugin-plugin/index.html) to generate documentation,
- a [Modello model](https://codehaus-plexus.github.io/modello/index.html) that can be converted in many other formats.

**Comment by vy** [comment]
> A loose list of metadata formats we might consider:
> 
> * an XML Schema itself,
> * a [Plexus component descriptor](https://codehaus-plexus.github.io/guides/developer-guide/configuration/index.html),
> * a [Maven plugin descriptor](https://maven.apache.org/ref/3.9.5/maven-plugin-api/plugin.html), which is used by the [Maven Plugin plugin](https://maven.apache.org/plugin-tools/maven-plugin-plugin/index.html) to generate documentation,
> * a [Modello model](https://codehaus-plexus.github.io/modello/index.html) that can be converted in many other formats.

@ppkarwasz, I completely support the research phase you described. Though I will also appreciate some non-Maven-native solutions (besides an XSD) too.

**Comment by ppkarwasz** [comment]
> @ppkarwasz, I completely support the research phase you described. Though I will also appreciate some non-Maven-native solutions (besides an XSD) too.

Sure thing, my research is not complete. Maven-related formats were just the easiest to find.

**Comment by jvz** [comment]
Neat, this is an idea I've had in the past. It would be great if we had proper XSDs that made it easier to edit a log4j configuration file. Might be useful to see if this schema can be represented as a JsonSchema, too, so it can be used for JSON and YAML configuration files.

One potential source of inspiration here would be whatever Spring Boot does for making your various `@ConfigurationProperties` classes autocomplete when modifying Spring properties configurations.

I should note that various old plugins still use strings for various plugin attributes that should be a different data type, but the initial plugin system only supported string values for attributes as it mimicked the DOM API here. Thus, if you use the type info of a plugin attribute, note that a string type is not necessarily authoritative.

**Comment by ppkarwasz** [comment]
The main plan here is to have a documentation like Maven plugins (e.g. [Maven Compiler Plugin](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html)). These are generated without a single line of text (besides the `*.java` files). I would like something like this for each plugin:

| Parameter | Type | Description |
|-----------------|---------|------------------|
| direct | boolean | Specifies whether to use `System.out/err` or the file descriptors |
| layout | Layout | The layout to use. Common layouts: list of links. (all layouts link) |

The XSD will be a byproduct of this process, but the metadata must be a little bit larger: in February-March we plan to write an online configuration builder/validation tool. This tool might also spit up a list of Maven dependencies required by the configuration.

**Comment by jvz** [comment]
Oh that all sounds fantastic!

**Comment by ppkarwasz** [comment]
A **second** requirement from the metadata format is the availability of tools to generate various formats of documentation:

- as far as I can tell OSGi Declarative Services do not have such tools,
- the was an [Eclipse EMF documentation generator](https://www.eclipse.org/forums/index.php/t/1110506/), but it does not seem available at the moment,
- [Tomcat Configuration Reference](https://tomcat.apache.org/tomcat-9.0-doc/config/index.html), which was the main inspiration for this task is actually generated manually (cf. [git repository](https://github.com/apache/tomcat/tree/main/webapps/docs/config)).

This leaves Modello that has an [impressive number of generators](https://codehaus-plexus.github.io/modello/modello-plugins/index.html) and the custom Maven Plugin descriptor as contenders. The [documentation of Maven Plugin descriptor](https://maven.apache.org/ref/3.9.5/maven-plugin-api/plugin.html) is actually generated by Modello.

**Comment by ppkarwasz** [comment]
An experiment performed using Modello (cf. the [Log4j Documentation Reference using Modello gist](https://gist.github.com/ppkarwasz/2b4df90cbad54c3d15adf4a524466e35)), shows that even if we use a Modello descriptor to describe Log4j plugins, we would need to write the documentation logic ourselves (even for "just" an XSD).

That is why I believe:

- we should still use Modello, but to generate **our own descriptor** that would not approximate our components as Java Beans, but use their natural representation (plugin + plugin builder with a separate hierarchy for each of them).

**Comment by vy** [comment]
How would you compare these solutions to simply rendering an XSD/JSON and mapping it to a `Map<String, Object>` passed to a [FreeMarker?] template where we can generate whatever plain-text (AsciiDoc, etc.) we want? I would rather have full control over model-to-AsciiDoc conversion, since we can tailor the emitted output as we see fit.

**Comment by vy** [comment]
1. `log4j-plugins` parses Log4j plugins and generates some sort of DOM model already – correct me if I am wrong. How would you compare us generating an XSD out of this DOM model versus decorating plugins with Modello and using Modello to generate an XSD?
2. When Modello is employed, do we need to use both Log4j and Modello annotations for plugins?

Given XSD is an XML too, I would favor simply passing XSD model to FreeMarker (through a simple `Map<String,Object>`?) and deal with _representation_ there.

**Comment by ppkarwasz** [comment]
> 1. `log4j-plugins` parses Log4j plugins and generates some sort of DOM model already – correct me if I am wrong. How would you compare us generating an XSD out of this DOM model versus decorating plugins with Modello and using Modello to generate an XSD?

I thought to use Modello **only** as an implementation detail. `log4j-plugins` will generate some XML (right now it generates Java code). We'll use Modello to parse these XML files and generate:

1. A common XSD for all the Log4j (and in the future third-party) modules,
2. A set of documentation pages.

>     2. When Modello is employed, do we need to use both Log4j and Modello annotations for plugins?

No, this will be transparent for the user.

> Given XSD is an XML too, I would favor simply passing XSD model to FreeMarker (through a simple `Map<String,Object>`?) and deal with _representation_ there.

The XSD schema will cover only part of our plugins (those in the "Core" namespace).

**Comment by ppkarwasz** [comment]
> This translates to
> 
> ```
> plugins --(Log4j)--> XML --(Modello)--> XSD
> ```
> 
> How would you compare this to the following?
> 
> ```
> plugins --(Log4j)--> XSD
> ```

Modello will only be used to generate code for XML serialization/deserialization and the model itself. Once that is done it will be:

```
Source code --(`log4j-plugins-processor`)--> XML --(`log4j-docgen`)--> XSD, Asciidoc et al.
```

**Comment by ppkarwasz** [comment]
With the submission of the PRs above, I consider this subtask complete.
