### ISSUE TITLE
log file overwritten and not correctly rolled (with log4j 2.20.0)

### ISSUE THREAD

**Issue by castriottaa** [apache/logging-log4j2#1958]
## Description

My java app configures log4j2 with the following instruction:

```java
org.apache.logging.log4j.core.config.Configurator.reconfigure(new File(iniDir, LOG4JBATCH_CONF).toURI());
```

The configuration is the following, with daily rolling strategy:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
	<Appenders>
		<Console name="console" target="SYSTEM_OUT">
			<PatternLayout pattern="%-5p %d{ISO8601} [%-t] [%c:%L] %m%n" />
		</Console>
		<RollingFile name="trace" fileName="${path.batch.log}/trace.log" filePattern="${path.batch.log}/trace.log-%d{yyyy-MM-dd}">
			<PatternLayout pattern="%-5p %d{ISO8601} [%-t] [%c:%L] %m%n" />
			<Policies>
				<TimeBasedTriggeringPolicy interval="1" modulate="true" />
			</Policies>
			<DefaultRolloverStrategy max="10" />
		</RollingFile>
		<RollingFile name="times" fileName="${path.batch.log}/times.log" filePattern="${path.batch.log}/times.log-%d{yyyy-MM-dd}">
			<PatternLayout pattern="%-5p %d{ISO8601} [%-t] [%c:%L] %m%n" />
			<Policies>
				<TimeBasedTriggeringPolicy interval="1" modulate="true" />
			</Policies>
			<DefaultRolloverStrategy max="10" />
		</RollingFile>
	</Appenders>
</Configuration>
```

Despite this, the trace.log of the previous day has been completely overwritten by the current execution, generating the following situation:

- trace.log-2023-11-08 => contains only the first line of the execution of the 2023-11-09 (all logs of 2023-11-08 are vanished)
- trace.log => contains the logs of the execution of the 2023-11-09 (from the second line!)

This is not happened the day before.

## Configuration

**Version:** 2.20.0

**Operating system:** Red Hat Enterprise Linux Server 7.5 (Maipo)

**JDK:** 

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

## Logs

NA

## Reproduction

It's not clear how it can be reproduced.

**Comment by ppkarwasz** [comment]
@castriottaa,

Does your application run 24/7 or do you restart it every day?
In the latter case you might be missing an [`OnStartupTriggeringPolicy`](https://logging.apache.org/log4j/2.x/javadoc/log4j-core/org/apache/logging/log4j/core/appender/rolling/OnStartupTriggeringPolicy.html).

**Comment by castriottaa** [comment]
@ppkarwasz My application is a batch that starts every day on event.
Probably you are right: that configuration is missing.
If you confirm that it manages the rollover of the log files, I only need to apply that.
So this should not be a bug, in that case.

**Comment by ppkarwasz** [comment]
@castriottaa,

Can you check if adding an `OnStartupTriggeringPolicy` solves the problem?

**Comment by castriottaa** [comment]
@ppkarwasz Until now it's not happened anymore. You can close this issue for now, thanks.

**Comment by ppkarwasz** [comment]
Thanks,

I am closing this.
