### ISSUE TITLE
2.21.1 tarball download files missing

### ISSUE THREAD

**Issue by rainerjung** [apache/logging-log4j2#1959]
Page https://logging.apache.org/log4j/2.x/download.html links tarballs and zip files for bin and src, but the tarball links are broken. In the actual download directories and archive only the zip files are present, not the tarballs.

**Comment by vy** [comment]
@rainerjung, thanks so much for the report. :bow: We have switched to a new release process and stopped producing TARs. I have removed their mention from the website.
