### ISSUE TITLE
Sync and move Java EE modules to a new repo in `3.x`

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1966]
Since `3.x` will have a Jakarta EE 9 baseline (like Spring Boot 3.x), we should move the following modules (with commit history) to a new repo:

- [ ] `log4j-jms`,
- [ ] `log4j-smtp`,
- [ ] `log4j-web`.

The new repo should be called `logging-log4j-jakarta`.

**Comment by ppkarwasz** [comment]
The `log4j-web` module is synchronized between `2.x` and `main` (actually `main` has an additional lookup feature):

- 05cd238b63ba4167760b5cb0293fd2fd145e4856
- aada21dae6a5db33951ed91663355907dad918a0
- 945cb7fecb48b35d16e375db58d8cda5dfd414e5

**Comment by ppkarwasz** [comment]
The `log4j-smtp` seems already up-to-date.

**Comment by ppkarwasz** [comment]
There are some differences in `log4j-jms`, but they seem newer than the version in `2.x`.

All three modules `log4j-jms`, `log4j-smtp` and `log4j-web` can be moved.

**Comment by vy** [comment]
* [logging-log4j-jakarta](/apache/logging-log4j-jakarta) repository is created with [a website](https://logging.staged.apache.org/log4j/jakarta)
* JEE modules are removed (#1981)
