### ISSUE TITLE
Custom ConfigurationFactory implementation added to the classpath are not loaded

### ISSUE THREAD

**Issue by thejas-stripe** [apache/logging-log4j2#1997]
## Description
The document [here](https://logging.apache.org/log4j/log4j-2.12.4/manual/customconfig.html) under `Understanding ConfigurationFactory` says 

```
3. A ConfigurationFactory implementation can be added to the classpath 
and configured as a plugin in the "ConfigurationFactory" category. 
The Order annotation can be used to specify the relative priority 
when multiple applicable ConfigurationFactories are found.
```

This is not true. We need to explicitly specify the packages to look for  using 

`PluginManager.addPackage("com.abc.xyl");` during start up before log4j initialization. 

This is not documented anywhere. 

## Configuration

**Version:** [2.22.0]

**Operating system:** [ALL]

**JDK:** [ALL]

## Reproduction
https://github.com/eugenp/tutorials/blob/master/logging-modules/log4j2/src/test/java/com/baeldung/logging/log4j2/xmlconfiguration/XMLConfigLogIntegrationTest.java#L24 

[An isolated test reproducing the test.
JUnit tests similar to the ones in the code base are extremely appreciated.]

**Comment by ppkarwasz** [comment]
@thejas-stripe,

In order to be automatically detected, plugins must be compiled with the annotation processor present in `log4j-core`. In your project you explicitly pass `-proc:none` to your compiler's options. Remove that line and your example should work.
