### ISSUE TITLE
[MS7] Branch `main` overhaul #2

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2016]
This story aims to build on the work delivered in #1969 and continue with following tasks:

- Improve queue factory interface (#2075)
- Address leftover recycler reviews (d029b335b024ca79d2b039ddd51af88c56350594, 47ff3fd4db475a0aec3ba761e3ebd72254f46b36, 716eca0128303cbbc1aac26a75d69590efc8bf02, 156b34e848253db7510048bf9c57a36e707bd9b0)
- Overhaul `main` (targeting Log4j version `3.0.0`) branch
  - Upgrade compiler baseline to Java 17 (77245ddae8e9ffc2b355def5d87ce4d8b61ac819)
  - Auxiliary support files (9651905cbefbc2a92c6b98ff41bc60e4959b1aff)
  - #2142
  - #2154
  - #2076 
  - Port changes from `2.x`:
    - [Port `log4j-jpl` changes from `2.x`](https://github.com/apache/logging-log4j2/commit/6eed880f20dcd6ff1e2e2198d8de5053c67462d1)
    - #2160
    - [Port `log4j-kubernetes` changes from `2.x`](https://github.com/apache/logging-log4j2/commit/64226fef0b6dae54d4e11d461f0805a4ace271d7)
    - #2164
    - #2159
    - #2158
    - #2156
    - #2018
    - #2150
    - #2015

**Comment by ppkarwasz** [comment]
I would also propose to bind #2076 to this task as a cleanup job.

The whole `log4j-slf4j-impl` should IMHO be removed from `3.x` or at least reimplemented in terms of `log4j-slf4j2-impl`.

**Comment by ppkarwasz** [comment]
I am currently working on:

- `log4j-script`,
- `log4j-slf4j-impl`,
- `log4j-slf4j2-impl`,
- `log4j-to-jul`

so I marked them as done to prevent collisions.

**Comment by ppkarwasz** [comment]
Related to this are PRs that remove additional dependencies from `log4j-core`:

- [ ] #2142 
- [ ] #2154

**Comment by grobmeier** [comment]
completed
