### ISSUE TITLE
Various tests abuse static state that no longer works

### ISSUE THREAD

**Issue by jvz** [apache/logging-log4j2#2022]
## Description

There are numerous tests that abuse static state, system properties, and implicit startup ordering, and I've had to disable them for now as my attempts at porting them to use appropriate test extension functionality is not working with the way these tests were written. Most of them are in log4j-1.2-api:

* `AutoConfigTest`
* `CategoryTest`
* `LoggerTest`
* `MapRewriteAppenderTest`
* `PropertiesRollingWithPropertiesTest`
* `RewriteAppenderTest`
* `XmlConfigurationTest`
* `XmlRollingWithPropertiesTest`

In log4j-core, I also had to disable the following:

* `Log4jLogEventNanoTimeTest`
* `ThreadContextDataInjectorTest`

I'm documenting these all here so that they are not forgotten.

Edit: note that this is related to https://github.com/apache/logging-log4j2/issues/1977.

**Comment by ppkarwasz** [comment]
They seem to be fixed now.
