### ISSUE TITLE
log4j2 record log to gz has gc lock error

### ISSUE THREAD

**Issue by marinesky** [apache/logging-log4j2#2074]
## log4j2 record log to gz has gc lock error
1524.916: Setting _needs_gc. Thread "VM Thread" 1 locked.
1524.932: Thread "Log4j2-TF-1-RollingFileManager-37" is performing GC after exiting critical section, 0 locked
{Heap before GC invocations=447 (full 3):
 PSYoungGen      total 1223168K, used 1078166K [0x000000079ff00000, 0x00000007f5400000, 0x00000007f5400000)
  eden space 1048576K, 100% used [0x000000079ff00000,0x00000007dff00000,0x00000007dff00000)
  from space 174592K, 16% used [0x00000007dff00000,0x00000007e1be5960,0x00000007ea980000)
  to   space 174592K, 0% used [0x00000007ea980000,0x00000007ea980000,0x00000007f5400000)
 ParOldGen       total 2796544K, used 322106K [0x00000006f5400000, 0x000000079ff00000, 0x000000079ff00000)
  object space 2796544K, 11% used [0x00000006f5400000,0x0000000708e8e8c0,0x000000079ff00000)
 Metaspace       used 72447K, capacity 76556K, committed 76928K, reserved 1116160K
  class space    used 8517K, capacity 9219K, committed 9344K, reserved 1048576K
2023-12-07T17:40:55.937+0800: 1524.936: [GC (GCLocker Initiated GC) [PSYoungGen: 1078166K->30353K(1223168K)] 1400272K->352731K(4019712K), 0.0250409 secs] [Times: user=0.08 sys=0.00, real=0.03 secs] 
Heap after GC invocations=447 (full 3):

## Configuration

**Version:** [Log4j 2.17]

**Operating system:** [CentOS 7.2 x64]

**JDK:** [Java(TM) SE Runtime Environment (build 1.8.0_391-b13)]

## Logs

```
[Stacktraces, errors, etc. relevant applications logs.]
```

**Comment by ppkarwasz** [comment]
@marinesky,

The GC log you attached doesn't point to any error condition. What problems are you experiencing?

**Comment by marinesky** [comment]
> fo
Thank you for replying, I have solved it, it is not a problem
