### ISSUE TITLE
Merge queue factory interfaces

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2075]
Right now there are multiple interfaces with a similar purpose in `main`:

- [`QueueFactory`](https://github.com/apache/logging-log4j2/blob/main/log4j-api/src/main/java/org/apache/logging/log4j/util/QueueFactory.java),
- [`QueueFactories.BoundedQueueFactory`](https://github.com/apache/logging-log4j2/blob/main/log4j-api/src/main/java/org/apache/logging/log4j/util/QueueFactories.java),
- [`BlockingQueueFactory`](https://github.com/apache/logging-log4j2/blob/main/log4j-core/src/main/java/org/apache/logging/log4j/core/async/BlockingQueueFactory.java).

I believe we should merge them into a single interface.

We should also move the two implementations of `BlockingQueueFactory` that depend on JCTools and Conversant Disruptor into their own modules. Since these implementations can be used in both `log4j-api` and `log4j-core` they should:

- be accessible via `ServiceLoader` and configurable via Log4j properties,
- be annotated as Log4j Plugins and configurable as Log4j plugins.

**Comment by vy** [comment]
This issue is (mostly) fixed by #2104:

* `QueueFactories` and `QueueFactory` are removed
* `BlockingQueueFactory` is left in `log4j-core` with a JCTools-based implementation in the new `log4j-jctools` module
