### ISSUE TITLE
[MS25] Unified date formatting #1

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2079]
Date formatting in Log4j uses different formats:

- older layouts use [`SimpleDateFormat`](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html),
- newer layouts use [`DateTimeFormatter`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html).

While these formatters use similar patterns, the usage of both formatters causes code deduplication and performance issues.

For logging purposes a single formatter would be enough, which would:

- separate the format specifiers into a "date" part and a "time" part,
- format and cache the "date" part once a day,
- format the "time" part using a highly optimized formatter.

**Comment by jaykataria1111** [comment]
Hi @ppkarwasz , is this issue still open, can you provide, some detail on this, maybe I can pick it up 😄

**Comment by grobmeier** [comment]
Rejected and resolved in #3139 and #3337
