### ISSUE TITLE
Java compatibility information is missing

### ISSUE THREAD

**Issue by QiuSoft** [apache/logging-log4j2#2121]
Which release is compatible with java17，i haven't find any relation info – @QiuSoft

In the current website, it is not clear which release supports which Java versions. Ideally runtime-vs-build requirements should be separately shared too. This information can be shared (preferably explicitly!) in [the download page](https://logging.apache.org/log4j/2.x/download.html). – @vy

**Comment by ppkarwasz** [comment]
All the current versions are:

- the 2.x branch supports from Java 8 to the latest one (currently 21),
- the 3.x branch supports from Java 17 to the latest one (currently 21).

**Comment by vy** [comment]
@QiuSoft, your question is a valid one. Unfortunately it is not clear anywhere in the website. I took the liberty to update your ticket in a way that would guide how to implement it.

**Comment by vy** [comment]
Fixed in #2480 (`main`) and #2487 (`2.x`).
