### ISSUE TITLE
Split CLI commands from `log4j-1.2-api` and `log4j-core`

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2131]
There are a couple of CLI commands in the current 2.x artifacts. Their code is not used by other Log4j components.

### `log4j-1.2-api`

`log4j-1.2-api` contains a [Log4j1ConfigurationConverter](https://github.com/apache/logging-log4j2/blob/2.x/log4j-1.2-api/src/main/java/org/apache/log4j/config/Log4j1ConfigurationConverter.java), which shares code with the old (and **disabled**) [`Log4j1ConfigurationFactory`](https://github.com/apache/logging-log4j2/blob/2.x/log4j-1.2-api/src/main/java/org/apache/log4j/config/Log4j1ConfigurationFactory.java). IMHO:

- both components and their dependencies should be removed in 3.x,
- their functionality should be moved to a separate component (in a new repo or `logging-log4j-transform`).

Remark that the new configuration factory used by `log4j-1.2-api` is based on [`org.apache.log4j.builders`](https://github.com/apache/logging-log4j2/tree/2.x/log4j-1.2-api/src/main/java/org/apache/log4j/builders) and is extensible.
With some minor adjustments to the `o.a.l.b.Builder` interface we can switch `Log4j1ConfigurationConverter` to the new infrastructure and use it in openrewrite/rewrite-logging-frameworks#48.

### `log4j-core`

Log4j Core contains a simple custom logger generator and an old copy of [remkop/picocli](https://github.com/remkop/picocli). This should also be removed from the main code and transfered to a new artifact.

**Comment by vy** [comment]
I support the proposed `log4j-1.2-api` changes.

> Log4j Core contains ... an old copy of [remkop/picocli](/remkop/picocli). This should also be ... transferred to a new artifact

Why do we create a `log4j-picocli` instead of using `info.picocli:picocli`?

**Comment by ppkarwasz** [comment]
@vy,

I meant to transfer the code that **used** Picocli to a new artifact and add `info.picocli:picocli` as a dependency.
Actually I have [a branch for this issue](https://github.com/ppkarwasz/logging-log4j2/tree/picocli), which is almost ready to be published.

I just don't know which repo should be used: a custom logger generator doesn't match the purpose of `logging-log4j-transform`, on the other hand `logging-log4j-tools` is for internal tools only.

**Comment by vy** [comment]
@ppkarwasz, if we are gonna totally remove it in `3.x`, I think we can lay down the separate artifact to `2.x` to rest in peace.

**Comment by ppkarwasz** [comment]
Closed in #2435
