### ISSUE TITLE
https://logging.apache.org/log4j/2.x/ has a broken link

### ISSUE THREAD

**Issue by ghueller** [apache/logging-log4j2#2149]
## Description

Page contains paragraph: Where are the release notes? linking to https://logging.apache.org/log4j/2.x/release-notes.adoc
however, link is dead, the real link should be https://logging.apache.org/log4j/2.x/release-notes.html
(note the extension)

I have searched https://logging.apache.org/log4j/2.x/support.html for Info where to file this and since I found nothing better, I am reporting this here as a bug.

**Comment by temple69** [comment]
I would like to work on this issue

**Comment by ppkarwasz** [comment]
@ghueller, thanks for the report.
@temple69, thanks for volunteering help. I believe that many links on that page should be checked.

**Comment by Gospel-c** [comment]
If this issue has not been resolved, I would like to work on it.

**Comment by temple69** [comment]
@Gospel-c You can work on it
@ppkarwasz reassign it to @Gospel-c  am not proficient in java thought the program was written in javascript

**Comment by temple69** [comment]
My bad thought it was a code fix did not know it was a documentation fix
