### ISSUE TITLE
JsonLogEventParser can not parse json log string with extendedStackTrace 

### ISSUE THREAD

**Issue by sanova** [apache/logging-log4j2#2162]
## Description
I’m trying to set up a log reader using JsonLayout. 
Everything is fine even using the JsonTemplateLayout class and replicating the JsonLayout json structure and removing unnecessary properties.
However, if the log has a stackTrace, the string is not parsed. The same problem occurs even when using JsonLayout directly, both with stringified stackTrace and without.

## Configuration
appender.filejson.layout.type = JsonLayout
appender.filejson.layout.compact = true
appender.filejson.layout.eventEol = true
appender.filejson.layout.complete = false
appender.filejson.layout.properties = false
appender.filejson.layout.propertiesAsList = false
appender.filejson.layout.locationInfo = true
appender.filejson.layout.includeStacktrace = true
appender.filejson.layout.stacktraceAsString = true
appender.filejson.layout.includeNullDelimiter = false
appender.filejson.layout.objectMessageAsJsonObject = true

**Version:** [Log4j version]
Version: 2.20.0

**Operating system:** [OS and version]
Debian 10

**JDK:** [JDK distribution and version]
java version "1.8.0_221

## Logs
Caused by: java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.core.jackson-databind@2.12.1.redhat-00001//com.fasterxml.jackson.databind.ObjectReader._assertNotNull(ObjectReader.java:2366)
	at com.fasterxml.jackson.core.jackson-databind@2.12.1.redhat-00001//com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1099)
	at com.fasterxml.jackson.core.jackson-databind@2.12.1.redhat-00001//com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1491)
	at deployment.basiccore.war//org.apache.logging.log4j.core.parser.AbstractJacksonLogEventParser.parseFrom(AbstractJacksonLogEventParser.java:38)
	at deployment.basiccore.war//org.apache.logging.log4j.core.parser.JsonLogEventParser.parseFrom(JsonLogEventParser.java:25)
	at deployment.basiccore.war//it.siag.basiccore.logs.LogManager.getLogByDates(LogManager.java:100)
	... 203 more

## Reproduction
Example json log string:
```
{
  "instant": {
    "epochSecond": 1704362220,
    "nanoOfSecond": 253185000
  },
  "thread": "default task-1",
  "level": "DEBUG",
  "loggerName": "it.siag.basiccore.logs.LogManager",
  "message": "Error retrieving log.. ",
  "thrown": {
    "commonElementCount": 0,
    "name": "java.lang.NullPointerException",
    "extendedStackTrace": "
java.lang.NullPointerException: null\n\tat it.siag.basiccore.logs.LogManager.getLastLogRows(LogManager.java:63) ~[classes:?]\n\
    .....
    ....."
  },
  "endOfBatch": false,
  "loggerFqcn": "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId": 150,
  "threadPriority": 5,
  "source": {
    "class": "it.siag.basiccore.logs.LogManager",
    "method": "getLastLogRows",
    "file": "LogManager.java",
    "line": 72,
    "classLoaderName": "deployment.basiccore.war"
  }
}
```

Code to parse line:

```
JsonLogEventParser parser = new JsonLogEventParser();
try (BufferedReader br = new BufferedReader(new FileReader(logFilePath))) {
	while (br.readLine() != null) {
	        // Get LOG Event from line
	        try {
			LogEvent logEvent = parser.parseFrom(br.readLine());
                        .....
                }
                catch(Exception x) {
			System.out.print("Error parsing log");
			throw x;
		}
       }
}   
catch(Exception e) {
	System.out.println(e.getStackTrace().toString());
	throw new RuntimeException(e);
}
```

**Comment by ppkarwasz** [comment]
You are calling [`BufferedReader#readLine()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/BufferedReader.html#readLine()) **twice** per loop iteration.

Try:
```java
JsonLogEventParser parser = new JsonLogEventParser();
try (BufferedReader br = new BufferedReader(new FileReader(logFilePath))) {
        String line;
	while ((line = br.readLine()) != null) {
	        // Get LOG Event from line
	        try {
			LogEvent logEvent = parser.parseFrom(line);
                        .....
                }
                catch(Exception x) {
			System.out.print("Error parsing log");
			throw x;
		}
       }
}   
catch(Exception e) {
	System.out.println(e.getStackTrace().toString());
	throw new RuntimeException(e);
}
```

You are also assuming that each log line has one JSON object, which might be wrong.

BTW: we are considering removing the whole `o.a.l.l.core.parser` package from `log4j-core` (cf. [this thread on `dev@logging`](https://lists.apache.org/thread/12w04yp1z779yn5wbxf84mnx4rsww5ko)).

**Comment by sanova** [comment]
Thank you for your answer. Yes you are right regarding reading buffered line twice. But error persists. It's related only to the stacktrace part of json. it works fine if stacktrace is not present. 
Anyway, if the parser package will be removed from core, i have to implement my own parser json log. 
Thank you for you support.

**Comment by sanova** [comment]
If the parser package will be removed from core i can close the issue

**Comment by vy** [comment]
@sanova, I recommend you to indeed roll out your own parser.

Back in the days when `JsonLayout` was the only JSON-formatted layout, it was possible to provide Jackson-annotated DTOs to parse `LogEvent`s. With the introduction of `JsonTemplateLayout`, the user is given full control over the JSON structure, hence it is not possible to provide a parser, since the structure is not known to Log4j.

@sanova, if I may ask, what is your use case? Why do you need to parse logs back into Log4j `LogEvent`s? What do you do with it?

**Comment by ppkarwasz** [comment]
For completeness' sake, the parser didn't disappear, it was moved to samples: [`log4j-samples-parser`](https://github.com/apache/logging-log4j-samples/tree/main/log4j-samples-parser).
