### ISSUE TITLE
Avoid a slow exception catch in JdkMapAdapterStringMap constructor

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2238]
### Discussed in https://github.com/apache/logging-log4j2/discussions/2235

<div type='discussions-op-text'>

<sup>Originally posted by **jdgenerix** January 24, 2024</sup>
The `org.apache.logging.log4j.core.impl.JdkMapAdapterStringMap` constructor is called from `org.apache.logging.log4j.core.impl.ThreadContextDataInjector` with an UnmodiableMap (`copy`) and the constructor is trying to modify and catch an exception to detect if this is an immutable Map.
This code is triggered a lot of time and could be more efficient.
Adding a package protected constructor which take the immutable boolean flag as an argument and using it from `ThreadContextDataInjector` would avoid this slow try catch.

```java
        @Override
        public ReadOnlyStringMap rawContextData() {
            final ReadOnlyThreadContextMap map = ThreadContext.getThreadContextMap();
            if (map instanceof ReadOnlyStringMap) {
                return (ReadOnlyStringMap) map;
            }
            // note: default ThreadContextMap is null
            final Map<String, String> copy = ThreadContext.getImmutableContext();
            return copy.isEmpty() ? ContextDataFactory.emptyFrozenContextData() : new JdkMapAdapterStringMap(copy);
        }


        public JdkMapAdapterStringMap(final Map<String, String> map) {
		this.map = Objects.requireNonNull(map, "map");
		try {
			map.replace(Strings.EMPTY, Strings.EMPTY, Strings.EMPTY);
		} catch (final UnsupportedOperationException ignored) {
			immutable = true;
		}
	}
```</div>

**Comment by ppkarwasz** [comment]
@jdgenerix,

Thank you for this report. Can you supply a PR to correct this?

**Comment by jdgenerix** [comment]
@ppkarwasz I'm sorry, i don't really see the optimzation you saw with `ReadOnlyThreadContextMap`.

**Comment by ppkarwasz** [comment]
@jdgenerix,

After looking better at the code the native storage of `DefaultThreadContextMap` is JDK's `Map`, so the only optimization possible is to create an additional constructor to `JdkMapAdapterStringMap` that takes an additional boolean `frozen` parameter.

The:

```java
            final ReadOnlyThreadContextMap map = ThreadContext.getThreadContextMap();
            if (map instanceof ReadOnlyStringMap) {
                return (ReadOnlyStringMap) map;
            }
```

is also wrong (a `ReadOnlyThreadContextMap` is a factory of `ReadOnlyStringMap` not a `ReadOnlyStringMap` itself) and should be:

```java
            final ReadOnlyThreadContextMap map = ThreadContext.getThreadContextMap();
            if (map != null) {
                return map.getReadOnlyContextData();
            }
```

**Comment by ppkarwasz** [comment]
@jdgenerix,

Can you check if the latest snapshot in the Maven repo `https://repository.apache.org/snapshots` solves your problem?

**Comment by jdgenerix** [comment]
@ppkarwasz Thank you.
I did a test and it looks fine to me.
