### ISSUE TITLE
The parameter `-Dlog4j2.debug` does not `take effect` in version `2.23.0`, and StatusLogger.debug will no longer print logs

### ISSUE THREAD

**Issue by panbingkun** [apache/logging-log4j2#2337]
## Description
When we upgraded `log4j2` from version `2.22.1` to `2.23.0` in Spark, we found that logs that could have been printed before are no longer being printed.

## Configuration
```
# This log4j config file is for integration test SparkConfPropagateSuite.
rootLogger.level = debug
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %p %c: %maxLen{%m}{512}%n%ex{8}%n
```

**Version:** [Log4j version]
2.23.0

**Operating system:** [OS and version]
`Ubuntu 22.04.4 LTS` And `macos Sonama 14.3.1`.

**JDK:** [JDK distribution and version]
JDK 17

## Logs

The following are the logs printed in version `2.22.1`:
```
...

TRACE StatusLogger DefaultConfiguration cleaning Appenders from 1 LoggerConfigs.
DEBUG StatusLogger Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@384ad17b OK
TRACE StatusLogger Reregistering MBeans after reconfigure. Selector=org.apache.logging.log4j.core.selector.ClassLoaderContextSelector@5852c06f
TRACE StatusLogger Reregistering context (1/1): '5ffd2b27' org.apache.logging.log4j.core.LoggerContext@31190526
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=StatusLogger'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=ContextSelector'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=Loggers,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=Appenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=AsyncAppenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=AsyncLoggerRingBuffer'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ffd2b27,component=Loggers,name=*,subtype=RingBuffer'
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ffd2b27
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ffd2b27,component=StatusLogger
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ffd2b27,component=ContextSelector
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ffd2b27,component=Loggers,name=
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ffd2b27,component=Appenders,name=console
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
TRACE StatusLogger Using DummyNanoClock for nanosecond timestamps.
DEBUG StatusLogger Reconfiguration complete for context[name=5ffd2b27] at URI /Users/yangjie01/Tools/4.0/spark-4.0.0-SNAPSHOT-bin-3.3.6/conf/log4j2.properties (org.apache.logging.log4j.core.LoggerContext@31190526) with optional ClassLoader: null
DEBUG StatusLogger Shutdown hook enabled. Registering a new one.
...
```

In version `2.23.0`, `StatusLogger` related logs are no longer printed, eg
```
DEBUG StatusLogger Reconfiguration complete for context[name=5ffd2b27] at URI /Users/yangjie01/Tools/4.0/spark-4.0.0-SNAPSHOT-bin-3.3.6/conf/log4j2.properties (org.apache.logging.log4j.core.LoggerContext@31190526) with optional ClassLoader: null
```
The above logs will no longer be output.

## Reproduction
The relevant upgrade PR in Spark is
https://github.com/apache/spark/pull/45292

## I found that it was caused by the following changes:
- log4j2 version `2.22.1`
  https://github.com/apache/logging-log4j2/blob/rel/2.22.1/log4j-api/src/main/java/org/apache/logging/log4j/spi/AbstractLogger.java#L252-L254
  <img width="627" alt="image" src="https://github.com/apache/spark/assets/15246973/5c8d7af0-20aa-46c5-b12f-4509b399e54f">

  https://github.com/apache/logging-log4j2/blob/rel/2.22.1/log4j-api/src/main/java/org/apache/logging/log4j/spi/AbstractLogger.java#L2336-L2346
  <img width="610" alt="image" src="https://github.com/apache/spark/assets/15246973/b657c031-76c3-41cf-ac89-8c022edd088f">

  https://github.com/apache/logging-log4j2/blob/8469975a4f2b1f8f1bd4f25ca6d1989a52aefc1b/log4j-api/src/main/java/org/apache/logging/log4j/status/StatusLogger.java#L480-L487
  <img width="606" alt="image" src="https://github.com/apache/spark/assets/15246973/c5aa7565-4e98-4318-8903-4a6906ecacc7">

  https://github.com/apache/logging-log4j2/blob/rel/2.22.1/log4j-api/src/main/java/org/apache/logging/log4j/status/StatusLogger.java#L82-L83
  <img width="801" alt="image" src="https://github.com/apache/spark/assets/15246973/98d2fc19-cae1-49ff-9acc-440af53dd0e1">

- log4j2 version `2.23.0`
  https://github.com/apache/logging-log4j2/blob/rel/2.23.0/log4j-api/src/main/java/org/apache/logging/log4j/status/StatusLogger.java#L747-L752
  <img width="607" alt="image" src="https://github.com/apache/spark/assets/15246973/eed58d74-90c8-4360-b1eb-178c22d3fcef">

- The related commit that caused this change is:
  <img width="801" alt="image" src="https://github.com/apache/spark/assets/15246973/530640cb-be78-493d-bf4b-a06c38ecb1f5">

### Is this change in line with our expectations? Or this is a bug?

**Comment by ppkarwasz** [comment]
@panbingkun,

In release `2.23.0` the `StatusLogger` was entirely rewritten to work around some circular dependency problems we were having.

This is clearly a bug (IMHO the implementation of `StatusLogger#getLevel` is faulty). Could you submit a PR?

**Comment by vy** [comment]
@panbingkun, no need to submit a PR. I am taking care of this.

**Comment by panbingkun** [comment]
> @panbingkun,
> 
> In release `2.23.0` the `StatusLogger` was entirely rewritten to work around some circular dependency problems we were having.
> 
> This is clearly a bug (IMHO the implementation of `StatusLogger#getLevel` is faulty). Could you submit a PR?

Okay, thank you very much for your reply.
Let me wait for the `next opportunity` for the `first submission` of `log4j2` 😄

**Comment by panbingkun** [comment]
> @panbingkun, no need to submit a PR. I am taking care of this.

Thanks.

**Comment by vy** [comment]
@panbingkun, I have merged the fix to `2.x` branch. Could you give the `2.23.1-SNAPSHOT` a try once [this CI job](/apache/logging-log4j2/actions/runs/8112360270) successfully completes, and share the outcome, please?

**Comment by panbingkun** [comment]
> @panbingkun, I have merged the fix to `2.x` branch. Could you give the `2.23.1-SNAPSHOT` a try once [this CI job](/apache/logging-log4j2/actions/runs/8112360270) successfully completes, and share the outcome, please?

Sure, let we to do it.

**Comment by vy** [comment]
> Sure, let we to do it now.

@panbingkun, the CI job has successfully completed – needed a kick. Would you mind giving `2.23.1-SNAPSHOT` a try and sharing the outcome, please?

**Comment by panbingkun** [comment]
> > Sure, let we to do it now.
> 
> @panbingkun, the CI job has successfully completed – needed a kick. Would you mind giving `2.23.1-SNAPSHOT` a try and sharing the outcome, please?

@vy @ppkarwasz 

After testing, it was found that it still did `not` output the expected log information.
I analyzed it and found that `StatusLogger.isEnable` is working properly now, but the method `StatusConsoleListener.log` still seems to have `some issues`, as follows:
https://github.com/apache/logging-log4j2/blob/c5420410df2741a7704a0efc8b77b25aca1ddea8/log4j-api/src/main/java/org/apache/logging/log4j/status/StatusConsoleListener.java#L135-L141
<img width="610" alt="image" src="https://github.com/apache/logging-log4j2/assets/15246973/00c9148a-ba4b-4358-873e-1c7959506f88">

The `above method` does not consider whether the `debugging mode` is turned on,
So, I proposed a follow-up pr: https://github.com/apache/logging-log4j2/pull/2340,
Because I only have a `rough understanding` of `log4j2`, if the above modifications are incorrect, please correct me. Thank you very much!
