### ISSUE TITLE
The `log4j2.messageFactory` property is ignored since 2.23.0

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2379]
## Description

Due to the changes in version `2.23.0`, specifying an alternative default message factory through the `log4j2.messageFactory`
property does not work any more.

**Comment by deepblueli** [comment]
hi @ppkarwasz, the default message factory also changed from ReusuableMessageFactory to ParameterizedMessageFactory when `log4j2.enable.threadlocals` is set to true. 

Given that `log4j2.messageFactory` property doesn't work now, is there any other way we can change to use ReusuableMessageFactory?

**Comment by lizongbo** [comment]
This new code doesn't make the log4j2.messageFactory configuration work.Please roll back the logic that read the proeprties configuration file earlier.

**Comment by lizongbo** [comment]
My project with version log4j2 2.23.1 almost caused a serious problem

The following code is the correct implementation for the previous one

```

    public static final Class<? extends MessageFactory> DEFAULT_MESSAGE_FACTORY_CLASS = createClassForProperty(
            "log4j2.messageFactory", ReusableMessageFactory.class, ParameterizedMessageFactory.class);

```

**Comment by lizongbo** [comment]
@vy need open this Issue again.

**Comment by lizongbo** [comment]
this new code is not support for use log4j-slf4j-impl

log4j-slf4j-impl\src\main\java\org\apache\logging\slf4j\Log4jLogger.java
log4j-slf4j-impl Log4jLogger use src/main/java/org/apache/logging/log4j/simple/SimpleLogger.java
not use src/main/java/org/apache/logging/log4j/core/Logger.java

**Comment by ppkarwasz** [comment]
@lizongbo,

Did you check the `2.24.0-SNAPSHOT`? Volkan's patch is not contained in version 2.23.1.

**Comment by lizongbo** [comment]
> @lizongbo,
> 
> Did you check the `2.24.0-SNAPSHOT`? Volkan's patch is not contained in version 2.23.1.

Thank fo your reply, When I use 2.24.0-SNAPSHOT from https://repository.apache.org/content/groups/snapshots/
then I ound that wokrs ok, 
I'll wait for 2.24.0 to be released as soon as possible.
