### ISSUE TITLE
Log messages with partially missing parameters

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2380]
Log4j version `2.20.0` did also log messages with missing parameters. A call like:

```java
logger.info("{}, {} and {}", 1, 2);
```

resulted in a partially replaced message: `1, 2, and {}`.

The behavior changed in `2.21.0` and should be restored for backward compatibility.

**Comment by SeasonPanPan** [comment]
I will work on this issue #2380 .

**Comment by ppkarwasz** [comment]
Thanks
