### ISSUE TITLE
Use non-commercial host for SslConfigurationTest

### ISSUE THREAD

**Issue by sdavids** [apache/logging-log4j2#2467]
While running the test suite my firewall alerted me with an outgoing request to `login.yahoo.com`.

https://github.com/apache/logging-log4j2/blob/3c423531c2395a1abff23215182459a3378b522a/log4j-core-test/src/test/java/org/apache/logging/log4j/core/net/ssl/SslConfigurationTest.java#L32

Would it make sense to use a non-commercial host here?

In 2013 reliable TLS hosts might have been rare but nowadays ...

---

I suggest `apache.org`.

Or considering a GitHub runner is building the release `github.com`—GitHub is a commercial entity though.

**Comment by vy** [comment]
@sdavids, thanks for the heads up. Fixed in c88a546125f80ce840e96008ae6b96050ff24a7e and c79cc7519c42fed2cfc01c943803d200a66fddd7 for `2.x` and `main`, respectively.
