### ISSUE TITLE
Fix links on web site

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2491]
On our website we should fix:

* **broken** links (`4xx`s),
* links to non-canonical URLs (`3xx`s).

Also some kind of canonicalization would be advised. Since we run on Apache with [`mod_dir`](https://httpd.apache.org/docs/current/mod/mod_dir.html) and [`mod_negotiation`](https://httpd.apache.org/docs/current/mod/mod_negotiation.html) my personal preference would be to:

* remove trailing `index` and `index.html` from internal links (exception: the relative 'index.html' should be converted in `./`)
* remove trailing `.html` from internal links. We might even internationalize some pages or provide machine-readable alternatives to HTML (e.g. SBOM if the client asks for `application/vnd.cyclonedx+xml`).

**Comment by ppkarwasz** [comment]
We might use some tool like [Screaming Frog](https://www.screamingfrog.co.uk/) to detect the broken links.

**Comment by vy** [comment]
@ppkarwasz, could you explain how we can use `<place-your-3rd-party-link-checker-SaaS-here>`? Do you suggest a maintainer creating a personal account and occasionally checking the report?

**Comment by ppkarwasz** [comment]
[Screaming Frog](https://www.screamingfrog.co.uk/) offered us a free of charge full license of their link checker (cc @grobmeier ). I will be running it regularly to fix the broken links on our website.

The first results using this tool:

- 676f03a4c4ff9ae81d7a0422468d2addfcf36d60
- 06f19c1d3dfb50663ff65e5008f428569c3e4e04
- d7e2365bdcfbb1584f0eb2508535015dbd600ea2
- 26a6242c41ee9adcd972c1faf234b2e61ef22cc7
- 99bb351ef3d40cb4dab38857d45ab633466afe75
- 1d43edce19e4ff0075272c2f84f070452251c41b
- 2a4add25ba79ebd7561fb416d7853267eb1a3c43
