### ISSUE TITLE
Create a `Learn Log4j in under 2 minutes!` page

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2507]
As agreed in [the site structure document](https://docs.google.com/document/d/10Fu7oqDzdM_D6LbexzwX9arh51Tic7AGvkWTQrL6jjQ/edit), create a _"Learn Log4j in under 2 minutes!"_ page with following goals in mind:

- Outline:
  - `pom.xml` entries
  - `logger.info()` (and `logger.atInfo()`, i.e., the fluent API)
  - Don’t use `toString()`
  - Don’t `printStackTrace()` – use last argument
  - Don’t string concatenate – use parameters
  - My first `log4j2.xml`
  - Provide quick links to manual pages for next steps
- Target `2.x`, port to `main`

**Comment by grobmeier** [comment]
Added some changes with:
85c61ca6e1ecce697697dbc3f62745f4d0e03d03
e6ef19f902483734f93b66d93b9532505e15cec1
69169e6176f83b7c199639c5635816ead4ce9a7a
e6ef19f902483734f93b66d93b9532505e15cec1
261b8949cd96529acdd9807c6132a07955e7db8a
