### ISSUE TITLE
Revamp the `Configuration` page

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2525]
Due to the fast development lifecycle of Log4j 2, the configuration options documented in the [configuration page](https://logging.apache.org/log4j/2.x/manual/configuration) and those effectively available in the code are currently out-of-sync.

The purpose of this task is to:

- [x] check the documentation of  [Log4j System Properties](https://logging.apache.org/log4j/2.x/manual/configuration.html#SystemProperties) with their usage in the code,
- [x] if they differ, fix either the documentation page or the code,
- [x] simplify and restructure the page.

## `Configuration` page outline

As agreed in [the site structure document](https://docs.google.com/document/d/10Fu7oqDzdM_D6LbexzwX9arh51Tic7AGvkWTQrL6jjQ/edit), revamp the _"Configuration"_ page such that

- Outline:
  - Supported formats
    - General structure of configuration file
    - How do formats map to each other?
  - Basics
    - Very briefly explain appender, logger, etc.
    - Refer to the “Architecture” page for details
  - Properties
    - Mention about fuzzy matching
    - List them in definition list (for main artifacts)
  - Recipes
    - Examples for common use cases
  -   Links to the “Guides” page contents
  - Programmatic configuration
- Fix [LOG4J2-3684](https://issues.apache.org/jira/browse/LOG4J2-3684)
- Target `2.x`, port to `main`

**Comment by ppkarwasz** [comment]
The following "documentation" problems were fixed by adapting the code to the documented behavior:

- [ ] #2481,
- [ ] #2517,
- [ ] #2550

**Comment by ppkarwasz** [comment]
The following documentation changes were applied:

- [ ] #2552
