### ISSUE TITLE
Official website down

### ISSUE THREAD

**Issue by PerfectSlayer** [apache/logging-log4j2#2727]
Hello,

Not sure where to report this but the related Apache website looks down:
![image](https://github.com/apache/logging-log4j2/assets/1766222/8b7f516f-535e-4195-a443-df72cf53bae6)

Sorry, I would have post it to the mailing list but I can't find them without the main website.

Best,
Bruce

**Comment by vy** [comment]
@PerfectSlayer, yes, thanks for the heads up. We are aware of the issue. It is an ASF-wide infrastructural problem, there are more project websites affected – INFRA is working on it. For the time being, you can use the **staging** website: https://logging.staged.apache.org

**Comment by PerfectSlayer** [comment]
Thanks for the staging link @vy !
Feel free to close the issue as it looks like things are being taken care of 👌

**Comment by vy** [comment]
As of this moment, website is back! :tada:
