### ISSUE TITLE
Disable programmatic configuration if `log4j1.compatibility` is `false` (LOG4J2-3467)

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2778]
This issue is moved from the [LOG4J2-3467](https://issues.apache.org/jira/browse/LOG4J2-3467) JIRA issue.

The `log4j-1.2-api` artifact is a bridge, whose main purpose is to forward Log4j 1 "API" calls to Log4j 2 API.

Version 2.17.2 of the artifact introduced support for configuring Log4j Core using the Log4j 1 `PropertyConfigurator` and `DOMConfigurator` classes.
This feature should be disabled by default and depend on the opt-in `log4j1.compatibility` property, because:

* many third-party **libraries** (not related to logging) take upon themselves the reconfiguration of Log4j 1. This steals the control of logging configuration from application developers (see [How to disable log4j programmatic reconfiguration from a 3rd party jar](https://stackoverflow.com/questions/78801614/how-to-disable-log4j-programmatic-reconfiguration-from-a-3rd-party-jar) for example).
* if some **applications** actually use those classes, they can always set `log4j1.compatibility` to `true`. This configuration property is also used to enable the scanning of the classpath for `log4j.properties` and `log4j.xml` files.

**Comment by garydgregory** [comment]
Sounds reasonable. This should be front-and-center in the release notes in a MINOR release, not a MAINTENANCE release as it is an important behavior breaking change.
