### ISSUE TITLE
[MS19] Google OSS-Fuzz integration 1/2

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2891]
[Fuzzing](https://en.wikipedia.org/wiki/Fuzzing) is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program. [OSS-Fuzz](https://github.com/google/oss-fuzz) is Google's automated platform to fuzz noteworthy F/OSS projects and it has been shown to be [capable of detecting Log4Shell in ~5 minutes with a one-line fuzz target](https://twitter.com/fhenneke/status/1470377931230875650?s=20). In this milestone, we delivered a fully-fledged OSS-Fuzz integration not just for Log4j, but also Log4cxx:

* [Fuzzing integration for Log4j](/apache/logging-log4j2/compare/2.x..fuzzing)
* Log4j integration to OSS-Fuzz (google/oss-fuzz#12304)
* [Fuzzing integration for Log4cxx](/apache/logging-log4cxx/compare/master..fuzzing)
* Log4cxx integration to OSS-Fuzz (google/oss-fuzz#12352)

We are in the process of troubleshooting issues related with the OSS-Fuzz infrastructure – see google/oss-fuzz#12349 and google/oss-fuzz#12417 for details. We will tackle these in the 2nd part of the OSS-Fuzz integration project, i.e., the 20th milestone (#2892).

**Comment by grobmeier** [comment]
thanks, completed
