### ISSUE TITLE
[MS20] Google OSS-Fuzz integration 2/2

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2892]
In #2891, we delivered the preliminary Google OSS-Fuzz integration for Log4j and Log4cxx projects. During development, we encountered several issues both on our end and on the Google side of things. Such that, [some even helped to spot serious problems on the OSS-Fuzz infrastructure](https://github.com/google/oss-fuzz/issues/12417#issuecomment-2358727691). Eventually, we managed to successfully complete the integration of both

- Log4j (google/oss-fuzz#12514)
- Log4cxx (google/oss-fuzz#12538)

This work was made a part of the associated official projects and this is reflected in their websites:

- [Log4j](https://logging.apache.org/log4j/2.x/development.html#fuzzing)
- [Log4cxx](https://github.com/apache/logging-log4cxx/blob/master/src/site/markdown/development/fuzzing.md)

**Comment by grobmeier** [comment]
Looks good to me, thanks!
