### ISSUE TITLE
Voir mon catalogue WhatsApp

### ISSUE THREAD

**Issue by Franetse7** [apache/logging-log4j2#2934]
Suivez ce lien pour voir notre catalogue dans WhatsApp : https://wa.me/c/22893879898

**Comment by ppkarwasz** [comment]
@garydgregory,

Di you report it?

**Comment by garydgregory** [comment]
I did not.

**Comment by garydgregory** [comment]
@ppkarwasz 
I blocked and reported the user/issue.
