### ISSUE TITLE
Wrong artifact ID for the JSON template layout in the docs

### ISSUE THREAD

**Issue by bennypi** [apache/logging-log4j2#3041]
## Description

The docs for the JSON template layout say that the artifact ID of the necessary library is `log4j-json-template-layout`, see https://logging.apache.org/log4j/2.x/manual/json-template-layout.html#usage. That is the wrong artifact ID, the correct one is `log4j-layout-template-json`.

**Comment by vy** [comment]
@bennypi, thanks so much for the report. I've fixed the problem on [the staging site](https://logging.staged.apache.org/log4j/2.x/manual/json-template-layout.html#usage), it is getting deployed to [the production site](https://logging.apache.org/log4j/2.x/manual/json-template-layout.html#usage) as we speak – see [this CI job](/apache/logging-log4j2/actions/runs/11130936813).

**Comment by bennypi** [comment]
Thanks for the prompt response and fix!
