### ISSUE TITLE
logging.a.o download page needs second parameter for gpg verify

### ISSUE THREAD

**Issue by sebbASF** [apache/logging-log4j2#3099]
The page at https://logging.apache.org/download.html says:

```for sigFile in *.asc; do gpg --verify $sigFile; done```

That is insecure; gpg verify needs two parameters: the .asc file and the artifact itself.

This is described here:
https://www.apache.org/info/verification.html#specify_both

There is a further issue that the verification instructions are unlikely to work on Windows.

**Comment by vy** [comment]
@sebbASF, thanks for the heads up! :bow: Fixed for both [l.a.o/download.html](https://logging.apache.org/download.html) and [l.a.o/logging-parent/release-review-instructions.html](https://logging.staged.apache.org/logging-parent/release-review-instructions.html).
