### ISSUE TITLE
Ununified document addresses

### ISSUE THREAD

**Issue by youngledo** [apache/logging-log4j2#3253]
I found two document addresses, what I can see directly is [https://logging.apache.org/log4j/2.x/index.html](https://logging.apache.org/log4j/2.x/index.html), What's not easy to find is
[https://logging.apache.org/log4j/2.12.x/](https://logging.apache.org/log4j/2.12.x/), But I have found that the two complement each other. Would you consider merging them?

And the latter is in some ways more detailed, I prefer the latter.

**Comment by ppkarwasz** [comment]
@youngledo,

The `/log4j/2.12.x` website contains the documentation of the `2.12.x` release. That release was a (very short-lived) branch with security-only fixes, that appeared in December 2021 and was discontinued on December 29th, 2021.

I am planning to remove the `/log4j/2.3.x` and `/log4j/2.12.x` websites in a couple of weeks (see [this `dev@logging` thread](https://lists.apache.org/thread/fw9rhhfd46z3jy630q9974xl13cflzlm)), but if you wish to move some content from that page to `/log4j/2.x`, feel free to open a PR. There is an `[Edit]` button on each page of the new website, which points you to the correct AsciiDoc source document.
